// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void openScrnSel_Animation(lv_obj_t * TargetObject, int delay);
void closeScrnSel_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_scrnMain
void ui_scrnMain_screen_init(void);
lv_obj_t * ui_scrnMain;
lv_obj_t * ui_pnlCtrl;
lv_obj_t * ui_lblOutput;
void ui_event_btnOutput(lv_event_t * e);
lv_obj_t * ui_btnOutput;
lv_obj_t * ui_lblBtnOut;
lv_obj_t * ui_pnlOutputData;
lv_obj_t * ui_lblOpData;
lv_obj_t * ui_pnlRc;
lv_obj_t * ui_pnlRcHdr;
lv_obj_t * ui_lblSre;
lv_obj_t * ui_lblRc1;
lv_obj_t * ui_lblRc2;
lv_obj_t * ui_lblRc3;
lv_obj_t * ui_lblRc4;
lv_obj_t * ui_lblRc1D;
lv_obj_t * ui_lblRc2D;
lv_obj_t * ui_lblRc3D;
lv_obj_t * ui_lblRc4D;
lv_obj_t * ui_pnlRcBrdr1;
lv_obj_t * ui_pnlRcBrdr2;
lv_obj_t * ui_pnlScrnSelMain;
void ui_event_btnToManual(lv_event_t * e);
lv_obj_t * ui_btnToManual;
lv_obj_t * ui_lblToManual;
void ui_event_btnToFaults(lv_event_t * e);
lv_obj_t * ui_btnToFaults;
lv_obj_t * ui_lblToFaults;
void ui_event_btnToCanbus(lv_event_t * e);
lv_obj_t * ui_btnToCanbus;
lv_obj_t * ui_lblToCanbus;
lv_obj_t * ui_pnlHdr;
lv_obj_t * ui_lblHdr;
void ui_event_ddNode(lv_event_t * e);
lv_obj_t * ui_ddNode;
void ui_event_btnWifi(lv_event_t * e);
lv_obj_t * ui_btnWifi;
void ui_event_swchScrnMain(lv_event_t * e);
lv_obj_t * ui_swchScrnMain;
lv_obj_t * ui_pnlCm;
lv_obj_t * ui_pnlCmHdr;
lv_obj_t * ui_lblCm;
lv_obj_t * ui_lblCm1;
lv_obj_t * ui_lblCm2;
lv_obj_t * ui_lblCm3;
lv_obj_t * ui_lblCm4;
lv_obj_t * ui_lblCm5;
lv_obj_t * ui_lblCm6;
lv_obj_t * ui_lblCmD1;
lv_obj_t * ui_lblCmD2;
lv_obj_t * ui_lblCmD3;
lv_obj_t * ui_lblCmD4;
lv_obj_t * ui_lblCmD5;
lv_obj_t * ui_lblCmD6;
lv_obj_t * ui_pnlCmBrdr2;
lv_obj_t * ui_pnlFlt;
lv_obj_t * ui_lblFlt;
lv_obj_t * ui_pnlFltD;
lv_obj_t * ui_lblFltD;
lv_obj_t * ui_pnlFtr;
lv_obj_t * ui_lblFtr;
lv_obj_t * ui_pnlWifi;
lv_obj_t * ui_ddWifi;
void ui_event_txtaPass(lv_event_t * e);
lv_obj_t * ui_txtaPass;
void ui_event_btnWifiConnect(lv_event_t * e);
lv_obj_t * ui_btnWifiConnect;
lv_obj_t * ui_lblConnect;
void ui_event_btnWifiCancel(lv_event_t * e);
lv_obj_t * ui_btnWifiCancel;
lv_obj_t * ui_lblWifiCancel;
void ui_event_kbWifi(lv_event_t * e);
lv_obj_t * ui_kbWifi;
void ui_event_btnKbSubmit(lv_event_t * e);
lv_obj_t * ui_btnKbSubmit;
void ui_event_btnKbClose(lv_event_t * e);
lv_obj_t * ui_btnKbClose;

// SCREEN: ui_scrnManu
void ui_scrnManu_screen_init(void);
lv_obj_t * ui_scrnManu;
lv_obj_t * ui_pnlMsp;
lv_obj_t * ui_pnlMspHdr;
lv_obj_t * ui_lblMspHdr;
lv_obj_t * ui_pnlMspVolts;
lv_obj_t * ui_lblMspTxtUp;
void ui_event_txtMspUpper(lv_event_t * e);
lv_obj_t * ui_txtMspUpper;
lv_obj_t * ui_pnlMspAmps;
lv_obj_t * ui_lblMspTxtLower;
void ui_event_txtMspLower(lv_event_t * e);
lv_obj_t * ui_txtMspLower;
lv_obj_t * ui_lblMspAuto;
void ui_event_btnMspWrite(lv_event_t * e);
lv_obj_t * ui_btnMspWrite;
lv_obj_t * ui_lblMspWriteBtn;
void ui_event_btnMspManual(lv_event_t * e);
lv_obj_t * ui_btnMspManual;
void ui_event_btnMspAuto(lv_event_t * e);
lv_obj_t * ui_btnMspAuto;
lv_obj_t * ui_lblMspManualbtn;
lv_obj_t * ui_lblMspAutobtn;
lv_obj_t * ui_pnlScrnSelManu;
void ui_event_btnToMainManu(lv_event_t * e);
lv_obj_t * ui_btnToMainManu;
lv_obj_t * ui_lblToMainManu;
void ui_event_btnToFltManu(lv_event_t * e);
lv_obj_t * ui_btnToFltManu;
lv_obj_t * ui_lblToFltManu;
void ui_event_btnToCanbusManu(lv_event_t * e);
lv_obj_t * ui_btnToCanbusManu;
lv_obj_t * ui_lblToCanbusManu;
lv_obj_t * ui_pnlHdrManual;
lv_obj_t * ui_lblHdr1;
void ui_event_ddNode1(lv_event_t * e);
lv_obj_t * ui_ddNode1;
void ui_event_swchScrnManu(lv_event_t * e);
lv_obj_t * ui_swchScrnManu;
lv_obj_t * ui_pnlRcManual;
lv_obj_t * ui_pnlRcManualHdr;
lv_obj_t * ui_lblRcManualHdr;
lv_obj_t * ui_lblRcm1;
lv_obj_t * ui_lblRcm2;
lv_obj_t * ui_lblRcm3;
lv_obj_t * ui_lblRcm4;
lv_obj_t * ui_lblRcm5;
lv_obj_t * ui_lblRcm6;
lv_obj_t * ui_lblRcmD1;
lv_obj_t * ui_lblRcmD2;
lv_obj_t * ui_lblRcmD3;
lv_obj_t * ui_lblRcmD4;
lv_obj_t * ui_lblRcmD5;
lv_obj_t * ui_lblRcmD6;
lv_obj_t * ui_pnlRcMBrdr1;
lv_obj_t * ui_pnlRcMBrdr2;
lv_obj_t * ui_pnlRcMBrdr3;
lv_obj_t * ui_pnlRec;
lv_obj_t * ui_lblRecHdr;
lv_obj_t * ui_lblMspHdr1;
void ui_event_chkRC1(lv_event_t * e);
lv_obj_t * ui_chkRC1;
void ui_event_chkRC2(lv_event_t * e);
lv_obj_t * ui_chkRC2;
void ui_event_chkRC3(lv_event_t * e);
lv_obj_t * ui_chkRC3;
void ui_event_chkRC3Shaft(lv_event_t * e);
lv_obj_t * ui_chkRC3Shaft;
void ui_event_chkRC4Shaft(lv_event_t * e);
lv_obj_t * ui_chkRC4Shaft;
void ui_event_chkRC4(lv_event_t * e);
lv_obj_t * ui_chkRC4;
void ui_event_kbManu(lv_event_t * e);
lv_obj_t * ui_kbManu;
void ui_event_btnKbSubmit1(lv_event_t * e);
lv_obj_t * ui_btnKbSubmit1;
void ui_event_btnKbClose1(lv_event_t * e);
lv_obj_t * ui_btnKbClose1;

// SCREEN: ui_scrnFaults
void ui_scrnFaults_screen_init(void);
lv_obj_t * ui_scrnFaults;
lv_obj_t * ui_pnlSysFaults;
lv_obj_t * ui_pnlSysFaultsHdr;
lv_obj_t * ui_lblSysFltHdr;
lv_obj_t * ui_pnlSysFaultsBody;
lv_obj_t * ui_pnlScrnSelFlt;
void ui_event_btnToMainFlt(lv_event_t * e);
lv_obj_t * ui_btnToMainFlt;
lv_obj_t * ui_lblToMainFlt;
void ui_event_btnToManuFlt(lv_event_t * e);
lv_obj_t * ui_btnToManuFlt;
lv_obj_t * ui_lblToManuFlt;
void ui_event_btnToCanFlt(lv_event_t * e);
lv_obj_t * ui_btnToCanFlt;
lv_obj_t * ui_lblToCanFlt;
lv_obj_t * ui_pnlHdrFlt;
lv_obj_t * ui_lblHdrFlt;
void ui_event_swchScrnFlt(lv_event_t * e);
lv_obj_t * ui_swchScrnFlt;
void ui_event_btnClearFlt(lv_event_t * e);
lv_obj_t * ui_btnClearFlt;
lv_obj_t * ui_lblClrFlts;
lv_obj_t * ui_tblFlt;

// SCREEN: ui_scrnCanbus
void ui_scrnCanbus_screen_init(void);
lv_obj_t * ui_scrnCanbus;
lv_obj_t * ui_pnlCanRx;
lv_obj_t * ui_pnlCanRxHdr;
lv_obj_t * ui_lblCanRxHdr;
lv_obj_t * ui_pnlCanRxBody;
lv_obj_t * ui_pnlScrnSelCanbus;
void ui_event_btnToMainCan(lv_event_t * e);
lv_obj_t * ui_btnToMainCan;
lv_obj_t * ui_lblToMainCan;
void ui_event_btnToManuCan(lv_event_t * e);
lv_obj_t * ui_btnToManuCan;
lv_obj_t * ui_lblToManuCan;
void ui_event_btnToFltCan(lv_event_t * e);
lv_obj_t * ui_btnToFltCan;
lv_obj_t * ui_lblToFltCan;
lv_obj_t * ui_pnlHdrCan;
lv_obj_t * ui_lblHdrCan;
void ui_event_swchScrnCanbus(lv_event_t * e);
lv_obj_t * ui_swchScrnCanbus;
lv_obj_t * ui_lblModeSelTx;
void ui_event_sldrModeSel(lv_event_t * e);
lv_obj_t * ui_sldrModeSel;
lv_obj_t * ui_lblModeSelRx;
lv_obj_t * ui_pnlCanTx;
lv_obj_t * ui_pnlCanTxHdr;
lv_obj_t * ui_lblCanTxHdr;
lv_obj_t * ui_pnlCanTxBody;
lv_obj_t * ui_tblCanRx;
lv_obj_t * ui_tblCanTx;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void openScrnSel_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 250);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -100, 43);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void closeScrnSel_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 250);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 43, -100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnOutput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        tglOutput(e);
        _ui_state_modify(ui_btnOutput, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_btnToManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnManu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToFaults(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnFaults, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToCanbus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnCanbus, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_ddNode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeNode(e);
    }
}
void ui_event_btnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_pnlWifi, _UI_BASIC_PROPERTY_POSITION_X,  0);
    }
}
void ui_event_swchScrnMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        openScrnSel_Animation(ui_pnlScrnSelMain, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        closeScrnSel_Animation(ui_pnlScrnSelMain, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_swchScrnMain, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        closeScrnSel_Animation(ui_pnlScrnSelMain, 0);
    }
}
void ui_event_txtaPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_kbWifi, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
}
void ui_event_btnWifiConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        connectWifi(e);
    }
}
void ui_event_btnWifiCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_pnlWifi, _UI_BASIC_PROPERTY_POSITION_X,  -480);
    }
}
void ui_event_kbWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_kbWifi, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnKbSubmit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_kbWifi, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnKbClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_kbWifi, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_txtMspUpper(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_kbManu, _UI_BASIC_PROPERTY_POSITION_Y,  0);
        _ui_keyboard_set_target(ui_kbManu,  ui_txtMspUpper);
    }
}
void ui_event_txtMspLower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_kbManu,  ui_txtMspLower);
    }
}
void ui_event_btnMspWrite(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        wrSetPoints(e);
    }
}
void ui_event_btnMspManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnMspManual, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnMspAuto, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_checked_set_text_value(ui_lblMspTxtUp, target, "Volts:", "");
        _ui_checked_set_text_value(ui_lblMspTxtLower, target, "Amps:", "");
        _ui_basic_set_property(ui_txtMspUpper, _UI_BASIC_PROPERTY_POSITION_X,  51);
        _ui_basic_set_property(ui_txtMspLower, _UI_BASIC_PROPERTY_POSITION_X,  51);
        _ui_basic_set_property(ui_txtMspUpper, _UI_BASIC_PROPERTY_WIDTH,  117);
        _ui_basic_set_property(ui_txtMspLower, _UI_BASIC_PROPERTY_WIDTH,  117);
    }
}
void ui_event_btnMspAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnMspAuto, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnMspManual, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_txtMspUpper, _UI_BASIC_PROPERTY_POSITION_X,  71);
        _ui_basic_set_property(ui_txtMspLower, _UI_BASIC_PROPERTY_POSITION_X,  71);
        _ui_basic_set_property(ui_txtMspLower, _UI_BASIC_PROPERTY_WIDTH,  97);
        _ui_basic_set_property(ui_txtMspUpper, _UI_BASIC_PROPERTY_WIDTH,  97);
        _ui_checked_set_text_value(ui_lblMspTxtLower, target, "Err Limit:", "");
        _ui_checked_set_text_value(ui_lblMspTxtUp, target, "Demand:", "");
    }
}
void ui_event_btnToMainManu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToFltManu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnFaults, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToCanbusManu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnCanbus, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_ddNode1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeNode(e);
    }
}
void ui_event_swchScrnManu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        openScrnSel_Animation(ui_pnlScrnSelManu, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        closeScrnSel_Animation(ui_pnlScrnSelManu, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_swchScrnManu, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        closeScrnSel_Animation(ui_pnlScrnSelManu, 0);
    }
}
void ui_event_chkRC1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        enableRC1(e);
    }
}
void ui_event_chkRC2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        enableRC2(e);
    }
}
void ui_event_chkRC3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_chkRC3Shaft, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        enableRC3(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_chkRC3Shaft, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_chkRC3Shaft, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_chkRC3Shaft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        enableRCShaft3(e);
    }
}
void ui_event_chkRC4Shaft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        enableRCShaft4(e);
    }
}
void ui_event_chkRC4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_chkRC4Shaft, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        enableRC4(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_chkRC4Shaft, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_chkRC4Shaft, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_kbManu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_kbManu, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnKbSubmit1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_kbManu, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnKbClose1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_kbManu, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnToMainFlt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToManuFlt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnManu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToCanFlt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnCanbus, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_swchScrnFlt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        openScrnSel_Animation(ui_pnlScrnSelFlt, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        closeScrnSel_Animation(ui_pnlScrnSelFlt, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_swchScrnFlt, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        closeScrnSel_Animation(ui_pnlScrnSelFlt, 0);
    }
}
void ui_event_btnClearFlt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        clearFlts(e);
    }
}
void ui_event_btnToMainCan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToManuCan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnManu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnToFltCan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_scrnFaults, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_swchScrnCanbus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        openScrnSel_Animation(ui_pnlScrnSelCanbus, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        closeScrnSel_Animation(ui_pnlScrnSelCanbus, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_swchScrnCanbus, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        closeScrnSel_Animation(ui_pnlScrnSelCanbus, 0);
    }
}
void ui_event_sldrModeSel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        chngCanDisp(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrnMain_screen_init();
    ui_scrnManu_screen_init();
    ui_scrnFaults_screen_init();
    ui_scrnCanbus_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrnMain);
}
