// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_scrnMain
void ui_scrnMain_screen_init(void);
lv_obj_t * ui_scrnMain;
lv_obj_t * ui_pnlHdr;
lv_obj_t * ui_lblHdr;
void ui_event_ddNode(lv_event_t * e);
lv_obj_t * ui_ddNode;
void ui_event_ddMenu(lv_event_t * e);
lv_obj_t * ui_ddMenu;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_pnlCtrl;
lv_obj_t * ui_lblOutput;
void ui_event_btnOutput(lv_event_t * e);
lv_obj_t * ui_btnOutput;
lv_obj_t * ui_lblBtnOut;
lv_obj_t * ui_pnlOutputData;
lv_obj_t * ui_lblOpData;
lv_obj_t * ui_pnlRc;
lv_obj_t * ui_pnlRcHdr;
lv_obj_t * ui_lblSre;
lv_obj_t * ui_lblRc1;
lv_obj_t * ui_lblRc2;
lv_obj_t * ui_lblRc3;
lv_obj_t * ui_lblRc4;
lv_obj_t * ui_lblRc1D;
lv_obj_t * ui_lblRc2D;
lv_obj_t * ui_lblRc3D;
lv_obj_t * ui_lblRc4D;
lv_obj_t * ui_pnlRcBrdr1;
lv_obj_t * ui_pnlRcBrdr2;
lv_obj_t * ui_pnlCm;
lv_obj_t * ui_pnlCmHdr;
lv_obj_t * ui_lblCm;
lv_obj_t * ui_lblCm1;
lv_obj_t * ui_lblCm2;
lv_obj_t * ui_lblCm3;
lv_obj_t * ui_lblCm4;
lv_obj_t * ui_lblCm5;
lv_obj_t * ui_lblCm6;
lv_obj_t * ui_lblCmD1;
lv_obj_t * ui_lblCmD2;
lv_obj_t * ui_lblCmD3;
lv_obj_t * ui_lblCmD4;
lv_obj_t * ui_lblCmD5;
lv_obj_t * ui_lblCmD6;
lv_obj_t * ui_pnlCmBrdr2;
lv_obj_t * ui_pnlFlt;
lv_obj_t * ui_lblFlt;
lv_obj_t * ui_pnlFltD;
lv_obj_t * ui_lblFltD;
lv_obj_t * ui_pnlNetStat;
lv_obj_t * ui_lblNetStat;
lv_obj_t * ui_pnlWifi;
lv_obj_t * ui_ddWifi;
void ui_event_txtaPass(lv_event_t * e);
lv_obj_t * ui_txtaPass;
void ui_event_btnWifiConnect(lv_event_t * e);
lv_obj_t * ui_btnWifiConnect;
lv_obj_t * ui_lblConnect;
void ui_event_btnWifiCancel(lv_event_t * e);
lv_obj_t * ui_btnWifiCancel;
lv_obj_t * ui_lblWifiCancel;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
void ui_event_btnKbSubmit(lv_event_t * e);
lv_obj_t * ui_btnKbSubmit;
void ui_event_btnKbClose(lv_event_t * e);
lv_obj_t * ui_btnKbClose;

// SCREEN: ui_scrnManu
void ui_scrnManu_screen_init(void);
lv_obj_t * ui_scrnManu;
lv_obj_t * ui_pnlHdr1;
lv_obj_t * ui_lblHdr1;
void ui_event_ddNode1(lv_event_t * e);
lv_obj_t * ui_ddNode1;
void ui_event_ddMenu1(lv_event_t * e);
lv_obj_t * ui_ddMenu1;
lv_obj_t * ui_pnlSre2;
lv_obj_t * ui_pnlSreHdr2;
lv_obj_t * ui_lblSre2;
lv_obj_t * ui_lblSreCl11;
lv_obj_t * ui_lblSreCl12;
lv_obj_t * ui_lblSreCl13;
lv_obj_t * ui_lblSreCl14;
lv_obj_t * ui_lblSreCl1D2;
lv_obj_t * ui_lblSreCl2D2;
lv_obj_t * ui_lblSreCl3D2;
lv_obj_t * ui_lblSreCl4D4;
lv_obj_t * ui_lblSreCl15;
lv_obj_t * ui_lblSreCl16;
lv_obj_t * ui_lblSreCl4D5;
lv_obj_t * ui_lblSreCl4D6;
lv_obj_t * ui_pnlSre3;
lv_obj_t * ui_pnlSreHdr3;
lv_obj_t * ui_lblSre3;

// SCREEN: ui_scrWifi
void ui_scrWifi_screen_init(void);
lv_obj_t * ui_scrWifi;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Dropdown2;
void ui_event_TextArea2(lv_event_t * e);
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ddNode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        nodeSelect(e);
    }
}
void ui_event_ddMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        chngScrn(e);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_pnlWifi, _UI_BASIC_PROPERTY_POSITION_X,  0);
    }
}
void ui_event_btnOutput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        tglOutput(e);
        _ui_state_modify(ui_btnOutput, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_txtaPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
}
void ui_event_btnWifiConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        connectWifi(e);
    }
}
void ui_event_btnWifiCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_pnlWifi, _UI_BASIC_PROPERTY_POSITION_X,  -480);
    }
}
void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnKbSubmit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_btnKbClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  160);
    }
}
void ui_event_ddNode1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        nodeSelect(e);
    }
}
void ui_event_ddMenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        chngScrn(e);
    }
}
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        openKeyboard(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrnMain_screen_init();
    ui_scrnManu_screen_init();
    ui_scrWifi_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrnMain);
}
