// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_scrnMain
void ui_scrnMain_screen_init(void);
extern lv_obj_t * ui_scrnMain;
extern lv_obj_t * ui_pnlHdr;
extern lv_obj_t * ui_lblHdr;
void ui_event_ddNode(lv_event_t * e);
extern lv_obj_t * ui_ddNode;
void ui_event_ddMenu(lv_event_t * e);
extern lv_obj_t * ui_ddMenu;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_pnlCtrl;
extern lv_obj_t * ui_lblOutput;
void ui_event_btnOutput(lv_event_t * e);
extern lv_obj_t * ui_btnOutput;
extern lv_obj_t * ui_lblBtnOut;
extern lv_obj_t * ui_pnlOutputData;
extern lv_obj_t * ui_lblOpData;
extern lv_obj_t * ui_pnlRc;
extern lv_obj_t * ui_pnlRcHdr;
extern lv_obj_t * ui_lblSre;
extern lv_obj_t * ui_lblRc1;
extern lv_obj_t * ui_lblRc2;
extern lv_obj_t * ui_lblRc3;
extern lv_obj_t * ui_lblRc4;
extern lv_obj_t * ui_lblRc1D;
extern lv_obj_t * ui_lblRc2D;
extern lv_obj_t * ui_lblRc3D;
extern lv_obj_t * ui_lblRc4D;
extern lv_obj_t * ui_pnlRcBrdr1;
extern lv_obj_t * ui_pnlRcBrdr2;
extern lv_obj_t * ui_pnlCm;
extern lv_obj_t * ui_pnlCmHdr;
extern lv_obj_t * ui_lblCm;
extern lv_obj_t * ui_lblCm1;
extern lv_obj_t * ui_lblCm2;
extern lv_obj_t * ui_lblCm3;
extern lv_obj_t * ui_lblCm4;
extern lv_obj_t * ui_lblCm5;
extern lv_obj_t * ui_lblCm6;
extern lv_obj_t * ui_lblCmD1;
extern lv_obj_t * ui_lblCmD2;
extern lv_obj_t * ui_lblCmD3;
extern lv_obj_t * ui_lblCmD4;
extern lv_obj_t * ui_lblCmD5;
extern lv_obj_t * ui_lblCmD6;
extern lv_obj_t * ui_pnlCmBrdr2;
extern lv_obj_t * ui_pnlFlt;
extern lv_obj_t * ui_lblFlt;
extern lv_obj_t * ui_pnlFltD;
extern lv_obj_t * ui_lblFltD;
extern lv_obj_t * ui_pnlNetStat;
extern lv_obj_t * ui_lblNetStat;
extern lv_obj_t * ui_pnlWifi;
extern lv_obj_t * ui_ddWifi;
void ui_event_txtaPass(lv_event_t * e);
extern lv_obj_t * ui_txtaPass;
void ui_event_btnWifiConnect(lv_event_t * e);
extern lv_obj_t * ui_btnWifiConnect;
extern lv_obj_t * ui_lblConnect;
void ui_event_btnWifiCancel(lv_event_t * e);
extern lv_obj_t * ui_btnWifiCancel;
extern lv_obj_t * ui_lblWifiCancel;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
void ui_event_btnKbSubmit(lv_event_t * e);
extern lv_obj_t * ui_btnKbSubmit;
void ui_event_btnKbClose(lv_event_t * e);
extern lv_obj_t * ui_btnKbClose;
// SCREEN: ui_scrnManu
void ui_scrnManu_screen_init(void);
extern lv_obj_t * ui_scrnManu;
extern lv_obj_t * ui_pnlHdr1;
extern lv_obj_t * ui_lblHdr1;
void ui_event_ddNode1(lv_event_t * e);
extern lv_obj_t * ui_ddNode1;
void ui_event_ddMenu1(lv_event_t * e);
extern lv_obj_t * ui_ddMenu1;
extern lv_obj_t * ui_pnlSre2;
extern lv_obj_t * ui_pnlSreHdr2;
extern lv_obj_t * ui_lblSre2;
extern lv_obj_t * ui_lblSreCl11;
extern lv_obj_t * ui_lblSreCl12;
extern lv_obj_t * ui_lblSreCl13;
extern lv_obj_t * ui_lblSreCl14;
extern lv_obj_t * ui_lblSreCl1D2;
extern lv_obj_t * ui_lblSreCl2D2;
extern lv_obj_t * ui_lblSreCl3D2;
extern lv_obj_t * ui_lblSreCl4D4;
extern lv_obj_t * ui_lblSreCl15;
extern lv_obj_t * ui_lblSreCl16;
extern lv_obj_t * ui_lblSreCl4D5;
extern lv_obj_t * ui_lblSreCl4D6;
extern lv_obj_t * ui_pnlSre3;
extern lv_obj_t * ui_pnlSreHdr3;
extern lv_obj_t * ui_lblSre3;
// SCREEN: ui_scrWifi
void ui_scrWifi_screen_init(void);
extern lv_obj_t * ui_scrWifi;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Dropdown2;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_hamburger_png);    // assets\Hamburger.png
LV_IMG_DECLARE(ui_img_wificon_png);    // assets\Wificon.png
LV_IMG_DECLARE(ui_img_canbus_png);    // assets\canbus.png
LV_IMG_DECLARE(ui_img_wificon2_png);    // assets\Wificon2.png

LV_FONT_DECLARE(ui_font_seg7Big);
LV_FONT_DECLARE(ui_font_seg7_18);
LV_FONT_DECLARE(ui_font_seg7_22pt);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
