// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"

void tglOutput(lv_event_t * e)
{
	// Your code here
}

void changeNode(lv_event_t * e)
{
	// Your code here
}

void openCanbus(lv_event_t * e)
{
	// Your code here
}

void connectWifi(lv_event_t * e)
{
	// Your code here
}

void wrSetPoints(lv_event_t * e)
{
	// Your code here
}

void enableRC1(lv_event_t * e)
{
	// Your code here
}

void enableRC2(lv_event_t * e)
{
	// Your code here
}

void enableRC3(lv_event_t * e)
{
	// Your code here
}

void enableRCShaft3(lv_event_t * e)
{
	// Your code here
}

void enableRCShaft4(lv_event_t * e)
{
	// Your code here
}

void enableRC4(lv_event_t * e)
{
	// Your code here
}

void clearFlts(lv_event_t * e)
{
	// Your code here
}

void chngCanDisp(lv_event_t * e)
{


}
