// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void nodeSelect(lv_event_t * e);
void chngScrn(lv_event_t * e);
void tglOutput(lv_event_t * e);
void connectWifi(lv_event_t * e);
void nodeSelect(lv_event_t * e);
void chngScrn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
