// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"

void nodeSelect(lv_event_t * e)
{
	// Your code here
}

void chngScrn(lv_event_t * e)
{
	// Your code here
}

void tglOutput(lv_event_t * e)
{
	// Your code here
}

void connectWifi(lv_event_t * e)
{
	// Your code here
}

void openKeyboard(lv_event_t * e)
{
	// Your code here
}
