<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<title>Tdi Power, Inc LiquaBlade Host Controller</title>
<link href="/tdi_lb.css" rel="stylesheet" type="text/css">
<script src="/liquabladedynavars.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img src="/tdi.gif" width="15%" alt="TdiPower"></div>


<div id="navcontainer">
<ul id="navlist">
<li id="active"><a href="/index.htm">Zone Status</a></li>
<li><a href="/modstat.htm">PSU Status</a></li>
<li><a href="/zonecfg.htm">Zone Cfg</a></li>
<li><a href="/protect/config.htm">Network Cfg</a></li>
</ul>
</div>