// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrnManu_screen_init(void)
{
    ui_scrnManu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnManu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrnManu, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrnManu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scrnManu, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrnManu, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlMsp = lv_obj_create(ui_scrnManu);
    lv_obj_set_width(ui_pnlMsp, 309);
    lv_obj_set_height(ui_pnlMsp, 108);
    lv_obj_set_x(ui_pnlMsp, 5);
    lv_obj_set_y(ui_pnlMsp, 53);
    lv_obj_clear_flag(ui_pnlMsp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlMsp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlMsp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlMsp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlMsp, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlMsp, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlMsp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlMsp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlMsp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlMsp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlMspHdr = lv_obj_create(ui_pnlMsp);
    lv_obj_set_width(ui_pnlMspHdr, 327);
    lv_obj_set_height(ui_pnlMspHdr, 46);
    lv_obj_set_x(ui_pnlMspHdr, 0);
    lv_obj_set_y(ui_pnlMspHdr, -29);
    lv_obj_set_align(ui_pnlMspHdr, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnlMspHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlMspHdr, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlMspHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlMspHdr, lv_color_hex(0x6D6E77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlMspHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlMspHdr, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlMspHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlMspHdr, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspHdr = lv_label_create(ui_pnlMspHdr);
    lv_obj_set_width(ui_lblMspHdr, lv_pct(80));
    lv_obj_set_height(ui_lblMspHdr, lv_pct(184));
    lv_obj_set_x(ui_lblMspHdr, 0);
    lv_obj_set_y(ui_lblMspHdr, 6);
    lv_obj_set_align(ui_lblMspHdr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMspHdr, "Mode Set Points");
    lv_obj_set_style_text_color(ui_lblMspHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMspHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblMspHdr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMspHdr, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlMspVolts = lv_obj_create(ui_pnlMsp);
    lv_obj_set_width(ui_pnlMspVolts, 174);
    lv_obj_set_height(ui_pnlMspVolts, 30);
    lv_obj_set_x(ui_pnlMspVolts, -59);
    lv_obj_set_y(ui_pnlMspVolts, -1);
    lv_obj_set_align(ui_pnlMspVolts, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlMspVolts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlMspVolts, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlMspVolts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlMspVolts, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlMspVolts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlMspVolts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlMspVolts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlMspVolts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlMspVolts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspTxtUp = lv_label_create(ui_pnlMspVolts);
    lv_obj_set_width(ui_lblMspTxtUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMspTxtUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_lblMspTxtUp, 6);
    lv_obj_set_x(ui_lblMspTxtUp, lv_pct(0));
    lv_label_set_text(ui_lblMspTxtUp, "Demand:");
    lv_obj_set_style_text_color(ui_lblMspTxtUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMspTxtUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMspUpper = lv_textarea_create(ui_pnlMspVolts);
    lv_obj_set_width(ui_txtMspUpper, 97);
    lv_obj_set_height(ui_txtMspUpper, lv_pct(110));
    lv_obj_set_x(ui_txtMspUpper, 71);
    lv_obj_set_y(ui_txtMspUpper, lv_pct(0));
    lv_obj_set_style_text_align(ui_txtMspUpper, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtMspUpper, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtMspUpper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_txtMspUpper, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_txtMspUpper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtMspUpper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtMspUpper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtMspUpper, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtMspUpper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlMspAmps = lv_obj_create(ui_pnlMsp);
    lv_obj_set_width(ui_pnlMspAmps, 174);
    lv_obj_set_height(ui_pnlMspAmps, 30);
    lv_obj_set_x(ui_pnlMspAmps, -59);
    lv_obj_set_y(ui_pnlMspAmps, 34);
    lv_obj_set_align(ui_pnlMspAmps, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlMspAmps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlMspAmps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlMspAmps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlMspAmps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlMspAmps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlMspAmps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlMspAmps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlMspAmps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlMspAmps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspTxtLower = lv_label_create(ui_pnlMspAmps);
    lv_obj_set_width(ui_lblMspTxtLower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMspTxtLower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_lblMspTxtLower, 6);
    lv_obj_set_x(ui_lblMspTxtLower, lv_pct(0));
    lv_label_set_text(ui_lblMspTxtLower, "Err Limit:");
    lv_obj_set_style_text_color(ui_lblMspTxtLower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMspTxtLower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMspLower = lv_textarea_create(ui_pnlMspAmps);
    lv_obj_set_width(ui_txtMspLower, 97);
    lv_obj_set_height(ui_txtMspLower, lv_pct(110));
    lv_obj_set_x(ui_txtMspLower, 71);
    lv_obj_set_y(ui_txtMspLower, lv_pct(0));
    lv_obj_set_style_text_align(ui_txtMspLower, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtMspLower, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtMspLower, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtMspLower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_txtMspLower, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_txtMspLower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtMspLower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtMspLower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtMspLower, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtMspLower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspAuto = lv_obj_create(ui_pnlMsp);
    lv_obj_set_width(ui_lblMspAuto, 119);
    lv_obj_set_height(ui_lblMspAuto, 84);
    lv_obj_set_x(ui_lblMspAuto, 165);
    lv_obj_set_y(ui_lblMspAuto, 20);
    lv_obj_clear_flag(ui_lblMspAuto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lblMspAuto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblMspAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblMspAuto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblMspAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMspAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMspAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMspAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMspAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMspWrite = lv_btn_create(ui_lblMspAuto);
    lv_obj_set_width(ui_btnMspWrite, lv_pct(100));
    lv_obj_set_height(ui_btnMspWrite, lv_pct(21));
    lv_obj_set_x(ui_btnMspWrite, lv_pct(0));
    lv_obj_set_y(ui_btnMspWrite, lv_pct(-24));
    lv_obj_set_align(ui_btnMspWrite, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnMspWrite, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnMspWrite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnMspWrite, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMspWrite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspWriteBtn = lv_label_create(ui_btnMspWrite);
    lv_obj_set_width(ui_lblMspWriteBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMspWriteBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMspWriteBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMspWriteBtn, "Write");

    ui_btnMspManual = lv_btn_create(ui_lblMspAuto);
    lv_obj_set_width(ui_btnMspManual, lv_pct(20));
    lv_obj_set_height(ui_btnMspManual, lv_pct(20));
    lv_obj_set_x(ui_btnMspManual, lv_pct(1));
    lv_obj_set_y(ui_btnMspManual, lv_pct(-2));
    lv_obj_add_flag(ui_btnMspManual, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnMspManual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnMspManual, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMspManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMspAuto = lv_btn_create(ui_lblMspAuto);
    lv_obj_set_width(ui_btnMspAuto, lv_pct(20));
    lv_obj_set_height(ui_btnMspAuto, lv_pct(20));
    lv_obj_set_x(ui_btnMspAuto, lv_pct(1));
    lv_obj_set_y(ui_btnMspAuto, lv_pct(30));
    lv_obj_add_state(ui_btnMspAuto, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_btnMspAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnMspAuto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnMspAuto, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMspAuto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspManualbtn = lv_label_create(ui_lblMspAuto);
    lv_obj_set_width(ui_lblMspManualbtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMspManualbtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMspManualbtn, 27);
    lv_obj_set_y(ui_lblMspManualbtn, -1);
    lv_label_set_text(ui_lblMspManualbtn, "MANUAL");
    lv_obj_set_style_text_color(ui_lblMspManualbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMspManualbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspAutobtn = lv_label_create(ui_lblMspAuto);
    lv_obj_set_width(ui_lblMspAutobtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMspAutobtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMspAutobtn, 27);
    lv_obj_set_y(ui_lblMspAutobtn, 24);
    lv_label_set_text(ui_lblMspAutobtn, "AUTO");
    lv_obj_set_style_text_color(ui_lblMspAutobtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMspAutobtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlScrnSelManu = lv_obj_create(ui_scrnManu);
    lv_obj_set_width(ui_pnlScrnSelManu, 140);
    lv_obj_set_height(ui_pnlScrnSelManu, 135);
    lv_obj_set_x(ui_pnlScrnSelManu, 0);
    lv_obj_set_y(ui_pnlScrnSelManu, -100);
    lv_obj_clear_flag(ui_pnlScrnSelManu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlScrnSelManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlScrnSelManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlScrnSelManu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlScrnSelManu, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlScrnSelManu, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlScrnSelManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlScrnSelManu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlScrnSelManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlScrnSelManu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlScrnSelManu, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlScrnSelManu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlScrnSelManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlScrnSelManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlScrnSelManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlScrnSelManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_pnlScrnSelManu, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlScrnSelManu, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlScrnSelManu, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlScrnSelManu, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_btnToMainManu = lv_btn_create(ui_pnlScrnSelManu);
    lv_obj_set_width(ui_btnToMainManu, lv_pct(100));
    lv_obj_set_height(ui_btnToMainManu, lv_pct(33));
    lv_obj_add_flag(ui_btnToMainManu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToMainManu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToMainManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToMainManu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToMainManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToMainManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToMainManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToMainManu = lv_label_create(ui_btnToMainManu);
    lv_obj_set_width(ui_lblToMainManu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToMainManu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToMainManu, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToMainManu, "Main");

    ui_btnToFltManu = lv_btn_create(ui_pnlScrnSelManu);
    lv_obj_set_width(ui_btnToFltManu, lv_pct(100));
    lv_obj_set_height(ui_btnToFltManu, lv_pct(33));
    lv_obj_set_x(ui_btnToFltManu, lv_pct(0));
    lv_obj_set_y(ui_btnToFltManu, lv_pct(33));
    lv_obj_add_flag(ui_btnToFltManu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToFltManu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToFltManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToFltManu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToFltManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToFltManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToFltManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToFltManu = lv_label_create(ui_btnToFltManu);
    lv_obj_set_width(ui_lblToFltManu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToFltManu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToFltManu, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToFltManu, "Faults");

    ui_btnToCanbusManu = lv_btn_create(ui_pnlScrnSelManu);
    lv_obj_set_width(ui_btnToCanbusManu, lv_pct(100));
    lv_obj_set_height(ui_btnToCanbusManu, lv_pct(33));
    lv_obj_set_x(ui_btnToCanbusManu, lv_pct(0));
    lv_obj_set_y(ui_btnToCanbusManu, lv_pct(66));
    lv_obj_add_flag(ui_btnToCanbusManu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToCanbusManu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToCanbusManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToCanbusManu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToCanbusManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToCanbusManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToCanbusManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToCanbusManu = lv_label_create(ui_btnToCanbusManu);
    lv_obj_set_width(ui_lblToCanbusManu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToCanbusManu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToCanbusManu, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToCanbusManu, "CANbus");

    ui_pnlHdrManual = lv_obj_create(ui_scrnManu);
    lv_obj_set_height(ui_pnlHdrManual, 46);
    lv_obj_set_width(ui_pnlHdrManual, lv_pct(100));
    lv_obj_clear_flag(ui_pnlHdrManual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHdrManual, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHdrManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlHdrManual, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHdrManual, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_pnlHdrManual, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHdrManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHdr1 = lv_label_create(ui_pnlHdrManual);
    lv_obj_set_width(ui_lblHdr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHdr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHdr1, 43);
    lv_obj_set_y(ui_lblHdr1, 0);
    lv_obj_set_align(ui_lblHdr1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblHdr1, "Astrodyne TDI eLink2 Node");
    lv_obj_set_style_text_color(ui_lblHdr1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHdr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddNode1 = lv_dropdown_create(ui_pnlHdrManual);
    lv_dropdown_set_options(ui_ddNode1, "1 \n2 \n3 \n4 ");
    lv_obj_set_width(ui_ddNode1, 46);
    lv_obj_set_height(ui_ddNode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddNode1, 19);
    lv_obj_set_y(ui_ddNode1, 0);
    lv_obj_set_align(ui_ddNode1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ddNode1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ddNode1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ddNode1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddNode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddNode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ddNode1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ddNode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddNode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddNode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddNode1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddNode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ddNode1), LV_TEXT_ALIGN_RIGHT,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(lv_dropdown_get_list(ui_ddNode1), LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swchScrnManu = lv_switch_create(ui_pnlHdrManual);
    lv_obj_set_width(ui_swchScrnManu, 40);
    lv_obj_set_height(ui_swchScrnManu, 40);
    lv_obj_set_style_bg_color(ui_swchScrnManu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnManu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_swchScrnManu, &ui_img_hamburger_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_swchScrnManu, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnManu, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swchScrnManu, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swchScrnManu, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swchScrnManu, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnManu, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pnlRcManual = lv_obj_create(ui_scrnManu);
    lv_obj_set_width(ui_pnlRcManual, 155);
    lv_obj_set_height(ui_pnlRcManual, 262);
    lv_obj_set_x(ui_pnlRcManual, 320);
    lv_obj_set_y(ui_pnlRcManual, 53);
    lv_obj_clear_flag(ui_pnlRcManual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRcManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRcManual, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlRcManual, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlRcManual, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlRcManual, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlRcManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlRcManual, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlRcManual, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_pnlRcManual, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlRcManual, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlRcManual, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlRcManual, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_pnlRcManualHdr = lv_obj_create(ui_pnlRcManual);
    lv_obj_set_width(ui_pnlRcManualHdr, 161);
    lv_obj_set_height(ui_pnlRcManualHdr, 40);
    lv_obj_set_x(ui_pnlRcManualHdr, 0);
    lv_obj_set_y(ui_pnlRcManualHdr, -24);
    lv_obj_set_align(ui_pnlRcManualHdr, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnlRcManualHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlRcManualHdr, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcManualHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlRcManualHdr, lv_color_hex(0x58586A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlRcManualHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlRcManualHdr, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlRcManualHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlRcManualHdr, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcManualHdr = lv_label_create(ui_pnlRcManualHdr);
    lv_obj_set_width(ui_lblRcManualHdr, lv_pct(113));
    lv_obj_set_height(ui_lblRcManualHdr, lv_pct(359));
    lv_obj_set_x(ui_lblRcManualHdr, 0);
    lv_obj_set_y(ui_lblRcManualHdr, 5);
    lv_obj_set_align(ui_lblRcManualHdr, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblRcManualHdr, "Reference Cells");
    lv_obj_set_style_text_color(ui_lblRcManualHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcManualHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblRcManualHdr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcManualHdr, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcm1 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcm1, -4);
    lv_obj_set_y(ui_lblRcm1, 19);
    lv_label_set_text(ui_lblRcm1, "1.");
    lv_obj_set_style_text_color(ui_lblRcm1, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcm1, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcm2 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcm2, -10);
    lv_obj_set_y(ui_lblRcm2, 57);
    lv_label_set_text(ui_lblRcm2, "2.");
    lv_obj_set_style_text_color(ui_lblRcm2, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcm2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcm3 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcm3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcm3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcm3, -10);
    lv_obj_set_y(ui_lblRcm3, 94);
    lv_label_set_text(ui_lblRcm3, "3.");
    lv_obj_set_style_text_color(ui_lblRcm3, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcm3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcm3, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcm4 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcm4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcm4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcm4, -10);
    lv_obj_set_y(ui_lblRcm4, 131);
    lv_label_set_text(ui_lblRcm4, "4.");
    lv_obj_set_style_text_color(ui_lblRcm4, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcm4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcm4, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcm5 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcm5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcm5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcm5, -10);
    lv_obj_set_y(ui_lblRcm5, 168);
    lv_label_set_text(ui_lblRcm5, "5.");
    lv_obj_set_style_text_color(ui_lblRcm5, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcm5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcm5, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcm6 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcm6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcm6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcm6, -10);
    lv_obj_set_y(ui_lblRcm6, 205);
    lv_label_set_text(ui_lblRcm6, "6.");
    lv_obj_set_style_text_color(ui_lblRcm6, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcm6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcm6, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcmD1 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcmD1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcmD1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcmD1, 25);
    lv_obj_set_y(ui_lblRcmD1, 19);
    lv_label_set_text(ui_lblRcmD1, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRcmD1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcmD1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcmD1, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcmD2 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcmD2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcmD2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcmD2, 25);
    lv_obj_set_y(ui_lblRcmD2, 57);
    lv_label_set_text(ui_lblRcmD2, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRcmD2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcmD2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcmD2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcmD3 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcmD3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcmD3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcmD3, 25);
    lv_obj_set_y(ui_lblRcmD3, 94);
    lv_label_set_text(ui_lblRcmD3, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRcmD3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcmD3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcmD3, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcmD4 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcmD4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcmD4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcmD4, 25);
    lv_obj_set_y(ui_lblRcmD4, 131);
    lv_label_set_text(ui_lblRcmD4, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRcmD4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcmD4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcmD4, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcmD5 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcmD5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcmD5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcmD5, 25);
    lv_obj_set_y(ui_lblRcmD5, 168);
    lv_label_set_text(ui_lblRcmD5, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRcmD5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcmD5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcmD5, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRcmD6 = lv_label_create(ui_pnlRcManual);
    lv_obj_set_width(ui_lblRcmD6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRcmD6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRcmD6, 25);
    lv_obj_set_y(ui_lblRcmD6, 205);
    lv_label_set_text(ui_lblRcmD6, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRcmD6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRcmD6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRcmD6, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRcMBrdr1 = lv_obj_create(ui_pnlRcManual);
    lv_obj_set_width(ui_pnlRcMBrdr1, 184);
    lv_obj_set_height(ui_pnlRcMBrdr1, 39);
    lv_obj_set_x(ui_pnlRcMBrdr1, 0);
    lv_obj_set_y(ui_pnlRcMBrdr1, -39);
    lv_obj_set_align(ui_pnlRcMBrdr1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlRcMBrdr1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRcMBrdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRcMBrdr1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcMBrdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRcMBrdr2 = lv_obj_create(ui_pnlRcManual);
    lv_obj_set_width(ui_pnlRcMBrdr2, 184);
    lv_obj_set_height(ui_pnlRcMBrdr2, 39);
    lv_obj_set_x(ui_pnlRcMBrdr2, 0);
    lv_obj_set_y(ui_pnlRcMBrdr2, 36);
    lv_obj_set_align(ui_pnlRcMBrdr2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlRcMBrdr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRcMBrdr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRcMBrdr2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcMBrdr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRcMBrdr3 = lv_obj_create(ui_pnlRcManual);
    lv_obj_set_width(ui_pnlRcMBrdr3, 184);
    lv_obj_set_height(ui_pnlRcMBrdr3, 45);
    lv_obj_set_x(ui_pnlRcMBrdr3, 0);
    lv_obj_set_y(ui_pnlRcMBrdr3, 112);
    lv_obj_set_align(ui_pnlRcMBrdr3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlRcMBrdr3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRcMBrdr3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRcMBrdr3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcMBrdr3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRec = lv_obj_create(ui_scrnManu);
    lv_obj_set_width(ui_pnlRec, 309);
    lv_obj_set_height(ui_pnlRec, 149);
    lv_obj_set_x(ui_pnlRec, 5);
    lv_obj_set_y(ui_pnlRec, 166);
    lv_obj_clear_flag(ui_pnlRec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRec, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRec, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlRec, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlRec, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlRec, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlRec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlRec, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlRec, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRecHdr = lv_obj_create(ui_pnlRec);
    lv_obj_set_width(ui_lblRecHdr, 327);
    lv_obj_set_height(ui_lblRecHdr, 38);
    lv_obj_set_x(ui_lblRecHdr, 0);
    lv_obj_set_y(ui_lblRecHdr, -29);
    lv_obj_set_align(ui_lblRecHdr, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_lblRecHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lblRecHdr, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblRecHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblRecHdr, lv_color_hex(0x6D6E77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblRecHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblRecHdr, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblRecHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblRecHdr, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMspHdr1 = lv_label_create(ui_lblRecHdr);
    lv_obj_set_width(ui_lblMspHdr1, lv_pct(80));
    lv_obj_set_height(ui_lblMspHdr1, lv_pct(762));
    lv_obj_set_x(ui_lblMspHdr1, 0);
    lv_obj_set_y(ui_lblMspHdr1, 5);
    lv_obj_set_align(ui_lblMspHdr1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMspHdr1, "Reference Electrode Config");
    lv_obj_set_style_text_color(ui_lblMspHdr1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMspHdr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblMspHdr1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMspHdr1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkRC1 = lv_checkbox_create(ui_pnlRec);
    lv_checkbox_set_text(ui_chkRC1, "Reference Cell 1");
    lv_obj_set_width(ui_chkRC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkRC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkRC1, -14);
    lv_obj_set_y(ui_chkRC1, 13);
    lv_obj_add_flag(ui_chkRC1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_chkRC1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkRC1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkRC1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkRC2 = lv_checkbox_create(ui_pnlRec);
    lv_checkbox_set_text(ui_chkRC2, "Reference Cell 2");
    lv_obj_set_width(ui_chkRC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkRC2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_chkRC2, -14);
    lv_obj_set_y(ui_chkRC2, 42);
    lv_obj_add_flag(ui_chkRC2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_chkRC2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkRC2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkRC2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkRC3 = lv_checkbox_create(ui_pnlRec);
    lv_checkbox_set_text(ui_chkRC3, "Reference Cell 3");
    lv_obj_set_width(ui_chkRC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkRC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkRC3, -14);
    lv_obj_set_y(ui_chkRC3, 71);
    lv_obj_add_flag(ui_chkRC3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_chkRC3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkRC3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkRC3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkRC3Shaft = lv_checkbox_create(ui_pnlRec);
    lv_checkbox_set_text(ui_chkRC3Shaft, "Shaft Md");
    lv_obj_set_width(ui_chkRC3Shaft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkRC3Shaft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_chkRC3Shaft, 71);
    lv_obj_set_x(ui_chkRC3Shaft, lv_pct(63));
    lv_obj_add_state(ui_chkRC3Shaft, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_chkRC3Shaft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_chkRC3Shaft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkRC3Shaft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkRC3Shaft, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_chkRC3Shaft, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_chkRC3Shaft, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_chkRC3Shaft, lv_color_hex(0x525252), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_chkRC3Shaft, 255, LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_border_color(ui_chkRC3Shaft, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_chkRC3Shaft, 255, LV_PART_INDICATOR | LV_STATE_DISABLED);

    ui_chkRC4Shaft = lv_checkbox_create(ui_pnlRec);
    lv_checkbox_set_text(ui_chkRC4Shaft, "Shaft Md");
    lv_obj_set_width(ui_chkRC4Shaft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkRC4Shaft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_chkRC4Shaft, 100);
    lv_obj_set_x(ui_chkRC4Shaft, lv_pct(63));
    lv_obj_add_state(ui_chkRC4Shaft, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_chkRC4Shaft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_chkRC4Shaft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkRC4Shaft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkRC4Shaft, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_chkRC4Shaft, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_chkRC4Shaft, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_chkRC4Shaft, lv_color_hex(0x525252), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_chkRC4Shaft, 255, LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_border_color(ui_chkRC4Shaft, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_chkRC4Shaft, 255, LV_PART_INDICATOR | LV_STATE_DISABLED);

    ui_chkRC4 = lv_checkbox_create(ui_pnlRec);
    lv_checkbox_set_text(ui_chkRC4, "Reference Cell 4");
    lv_obj_set_width(ui_chkRC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkRC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkRC4, -14);
    lv_obj_set_y(ui_chkRC4, 100);
    lv_obj_add_flag(ui_chkRC4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_chkRC4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkRC4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkRC4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kbManu = lv_keyboard_create(ui_scrnManu);
    lv_obj_set_width(ui_kbManu, lv_pct(100));
    lv_obj_set_height(ui_kbManu, lv_pct(50));
    lv_obj_set_x(ui_kbManu, 0);
    lv_obj_set_y(ui_kbManu, 160);
    lv_obj_set_align(ui_kbManu, LV_ALIGN_BOTTOM_MID);

    ui_btnKbSubmit1 = lv_btn_create(ui_kbManu);
    lv_obj_set_width(ui_btnKbSubmit1, 65);
    lv_obj_set_height(ui_btnKbSubmit1, 35);
    lv_obj_set_align(ui_btnKbSubmit1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_btnKbSubmit1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKbSubmit1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKbSubmit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKbSubmit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnKbSubmit1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnKbSubmit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnKbClose1 = lv_btn_create(ui_kbManu);
    lv_obj_set_width(ui_btnKbClose1, 65);
    lv_obj_set_height(ui_btnKbClose1, 35);
    lv_obj_set_align(ui_btnKbClose1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btnKbClose1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKbClose1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKbClose1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKbClose1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnKbClose1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnKbClose1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_txtMspUpper, ui_event_txtMspUpper, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtMspLower, ui_event_txtMspLower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnMspWrite, ui_event_btnMspWrite, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnMspManual, ui_event_btnMspManual, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnMspAuto, ui_event_btnMspAuto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToMainManu, ui_event_btnToMainManu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToFltManu, ui_event_btnToFltManu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToCanbusManu, ui_event_btnToCanbusManu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddNode1, ui_event_ddNode1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swchScrnManu, ui_event_swchScrnManu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkRC1, ui_event_chkRC1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkRC2, ui_event_chkRC2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkRC3, ui_event_chkRC3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkRC3Shaft, ui_event_chkRC3Shaft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkRC4Shaft, ui_event_chkRC4Shaft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkRC4, ui_event_chkRC4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnKbSubmit1, ui_event_btnKbSubmit1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnKbClose1, ui_event_btnKbClose1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_kbManu, ui_event_kbManu, LV_EVENT_ALL, NULL);

}
