// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrnMain_screen_init(void)
{
    ui_scrnMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrnMain, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrnMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scrnMain, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrnMain, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlCtrl = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlCtrl, 153);
    lv_obj_set_height(ui_pnlCtrl, 80);
    lv_obj_set_x(ui_pnlCtrl, 10);
    lv_obj_set_y(ui_pnlCtrl, 55);
    lv_obj_clear_flag(ui_pnlCtrl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlCtrl, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlCtrl, lv_color_hex(0x81808C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_pnlCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_pnlCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlCtrl, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlCtrl, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlCtrl, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlCtrl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlCtrl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlCtrl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOutput = lv_label_create(ui_pnlCtrl);
    lv_obj_set_width(ui_lblOutput, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOutput, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOutput, -11);
    lv_obj_set_y(ui_lblOutput, -4);
    lv_label_set_text(ui_lblOutput, "Output");
    lv_obj_set_style_text_color(ui_lblOutput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOutput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnOutput = lv_btn_create(ui_pnlCtrl);
    lv_obj_set_width(ui_btnOutput, 54);
    lv_obj_set_height(ui_btnOutput, 25);
    lv_obj_set_x(ui_btnOutput, 13);
    lv_obj_set_y(ui_btnOutput, -9);
    lv_obj_set_align(ui_btnOutput, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_state(ui_btnOutput, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_btnOutput, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnOutput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnOutput, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOutput, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnOutput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnOutput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOutput, lv_color_hex(0x0DC601), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnOutput, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblBtnOut = lv_label_create(ui_btnOutput);
    lv_obj_set_width(ui_lblBtnOut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtnOut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBtnOut, 0);
    lv_obj_set_y(ui_lblBtnOut, 1);
    lv_obj_set_align(ui_lblBtnOut, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtnOut, "On");
    lv_obj_add_state(ui_lblBtnOut, LV_STATE_CHECKED);       /// States

    ui_pnlOutputData = lv_obj_create(ui_pnlCtrl);
    lv_obj_set_width(ui_pnlOutputData, 160);
    lv_obj_set_height(ui_pnlOutputData, 46);
    lv_obj_set_x(ui_pnlOutputData, 0);
    lv_obj_set_y(ui_pnlOutputData, 26);
    lv_obj_set_align(ui_pnlOutputData, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_pnlOutputData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlOutputData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlOutputData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlOutputData, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlOutputData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlOutputData, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlOutputData, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOpData = lv_label_create(ui_pnlOutputData);
    lv_obj_set_width(ui_lblOpData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOpData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOpData, 0);
    lv_obj_set_y(ui_lblOpData, 3);
    lv_obj_set_align(ui_lblOpData, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblOpData, "135.65 V 156.84 A");
    lv_obj_set_style_text_color(ui_lblOpData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOpData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOpData, &ui_font_seg7_22pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRc = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlRc, 155);
    lv_obj_set_height(ui_pnlRc, 171);
    lv_obj_set_x(ui_pnlRc, 10);
    lv_obj_set_y(ui_pnlRc, 141);
    lv_obj_clear_flag(ui_pnlRc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlRc, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlRc, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlRc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlRc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlRc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlRc, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRcHdr = lv_obj_create(ui_pnlRc);
    lv_obj_set_width(ui_pnlRcHdr, 161);
    lv_obj_set_height(ui_pnlRcHdr, 43);
    lv_obj_set_x(ui_pnlRcHdr, 0);
    lv_obj_set_y(ui_pnlRcHdr, -24);
    lv_obj_set_align(ui_pnlRcHdr, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnlRcHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlRcHdr, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlRcHdr, lv_color_hex(0x58586A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlRcHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlRcHdr, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlRcHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlRcHdr, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSre = lv_label_create(ui_pnlRcHdr);
    lv_obj_set_width(ui_lblSre, lv_pct(113));
    lv_obj_set_height(ui_lblSre, lv_pct(141));
    lv_obj_set_x(ui_lblSre, 0);
    lv_obj_set_y(ui_lblSre, 2);
    lv_obj_set_align(ui_lblSre, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblSre, "Reference Cells");
    lv_obj_set_style_text_color(ui_lblSre, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSre, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSre, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc1 = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc1, 0);
    lv_obj_set_y(ui_lblRc1, 19);
    lv_label_set_text(ui_lblRc1, "1.");
    lv_obj_set_style_text_color(ui_lblRc1, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc1, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc2 = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc2, -10);
    lv_obj_set_y(ui_lblRc2, 53);
    lv_label_set_text(ui_lblRc2, "2.");
    lv_obj_set_style_text_color(ui_lblRc2, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc3 = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc3, -10);
    lv_obj_set_y(ui_lblRc3, 85);
    lv_label_set_text(ui_lblRc3, "3.");
    lv_obj_set_style_text_color(ui_lblRc3, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc3, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc4 = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc4, -10);
    lv_obj_set_y(ui_lblRc4, 118);
    lv_label_set_text(ui_lblRc4, "4.");
    lv_obj_set_style_text_color(ui_lblRc4, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc4, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc1D = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc1D, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc1D, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc1D, 25);
    lv_obj_set_y(ui_lblRc1D, 20);
    lv_label_set_text(ui_lblRc1D, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRc1D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc1D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc1D, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc2D = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc2D, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc2D, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc2D, 25);
    lv_obj_set_y(ui_lblRc2D, 53);
    lv_label_set_text(ui_lblRc2D, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRc2D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc2D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc2D, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc3D = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc3D, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc3D, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc3D, 25);
    lv_obj_set_y(ui_lblRc3D, 86);
    lv_label_set_text(ui_lblRc3D, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRc3D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc3D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc3D, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRc4D = lv_label_create(ui_pnlRc);
    lv_obj_set_width(ui_lblRc4D, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRc4D, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRc4D, 25);
    lv_obj_set_y(ui_lblRc4D, 118);
    lv_label_set_text(ui_lblRc4D, "143.34 V");
    lv_obj_set_style_text_color(ui_lblRc4D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRc4D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRc4D, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRcBrdr1 = lv_obj_create(ui_pnlRc);
    lv_obj_set_width(ui_pnlRcBrdr1, 184);
    lv_obj_set_height(ui_pnlRcBrdr1, 34);
    lv_obj_set_x(ui_pnlRcBrdr1, 0);
    lv_obj_set_y(ui_pnlRcBrdr1, 3);
    lv_obj_set_align(ui_pnlRcBrdr1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlRcBrdr1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRcBrdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRcBrdr1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcBrdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlRcBrdr2 = lv_obj_create(ui_pnlRc);
    lv_obj_set_width(ui_pnlRcBrdr2, 184);
    lv_obj_set_height(ui_pnlRcBrdr2, 47);
    lv_obj_set_x(ui_pnlRcBrdr2, 0);
    lv_obj_set_y(ui_pnlRcBrdr2, 74);
    lv_obj_set_align(ui_pnlRcBrdr2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlRcBrdr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlRcBrdr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlRcBrdr2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlRcBrdr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlScrnSelMain = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlScrnSelMain, 140);
    lv_obj_set_height(ui_pnlScrnSelMain, 135);
    lv_obj_set_x(ui_pnlScrnSelMain, 0);
    lv_obj_set_y(ui_pnlScrnSelMain, -100);
    lv_obj_clear_flag(ui_pnlScrnSelMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlScrnSelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlScrnSelMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlScrnSelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlScrnSelMain, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlScrnSelMain, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlScrnSelMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlScrnSelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlScrnSelMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlScrnSelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlScrnSelMain, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlScrnSelMain, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlScrnSelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlScrnSelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlScrnSelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlScrnSelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_pnlScrnSelMain, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlScrnSelMain, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlScrnSelMain, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlScrnSelMain, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_btnToManual = lv_btn_create(ui_pnlScrnSelMain);
    lv_obj_set_width(ui_btnToManual, lv_pct(100));
    lv_obj_set_height(ui_btnToManual, lv_pct(33));
    lv_obj_add_flag(ui_btnToManual, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToManual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToManual, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToManual, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToManual = lv_label_create(ui_btnToManual);
    lv_obj_set_width(ui_lblToManual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToManual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToManual, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToManual, "Manual");

    ui_btnToFaults = lv_btn_create(ui_pnlScrnSelMain);
    lv_obj_set_width(ui_btnToFaults, lv_pct(100));
    lv_obj_set_height(ui_btnToFaults, lv_pct(33));
    lv_obj_set_x(ui_btnToFaults, lv_pct(0));
    lv_obj_set_y(ui_btnToFaults, lv_pct(33));
    lv_obj_add_flag(ui_btnToFaults, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToFaults, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToFaults, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToFaults, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToFaults = lv_label_create(ui_btnToFaults);
    lv_obj_set_width(ui_lblToFaults, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToFaults, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToFaults, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToFaults, "Faults");

    ui_btnToCanbus = lv_btn_create(ui_pnlScrnSelMain);
    lv_obj_set_width(ui_btnToCanbus, lv_pct(100));
    lv_obj_set_height(ui_btnToCanbus, lv_pct(33));
    lv_obj_set_x(ui_btnToCanbus, lv_pct(0));
    lv_obj_set_y(ui_btnToCanbus, lv_pct(66));
    lv_obj_add_flag(ui_btnToCanbus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToCanbus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToCanbus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToCanbus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToCanbus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToCanbus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToCanbus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToCanbus = lv_label_create(ui_btnToCanbus);
    lv_obj_set_width(ui_lblToCanbus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToCanbus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToCanbus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToCanbus, "CANbus");

    ui_pnlHdr = lv_obj_create(ui_scrnMain);
    lv_obj_set_height(ui_pnlHdr, 46);
    lv_obj_set_width(ui_pnlHdr, lv_pct(100));
    lv_obj_clear_flag(ui_pnlHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHdr, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHdr, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_pnlHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHdr = lv_label_create(ui_pnlHdr);
    lv_obj_set_width(ui_lblHdr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHdr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHdr, 43);
    lv_obj_set_y(ui_lblHdr, 0);
    lv_obj_set_align(ui_lblHdr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblHdr, "Astrodyne TDI eLink2 Node");
    lv_obj_set_style_text_color(ui_lblHdr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddNode = lv_dropdown_create(ui_pnlHdr);
    lv_dropdown_set_options(ui_ddNode, "1 \n2 \n3 \n4 ");
    lv_obj_set_width(ui_ddNode, 46);
    lv_obj_set_height(ui_ddNode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddNode, 19);
    lv_obj_set_y(ui_ddNode, 0);
    lv_obj_set_align(ui_ddNode, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ddNode, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ddNode, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ddNode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddNode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddNode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ddNode, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ddNode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddNode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddNode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddNode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddNode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ddNode), LV_TEXT_ALIGN_RIGHT,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(lv_dropdown_get_list(ui_ddNode), LV_TEXT_DECOR_UNDERLINE,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifi = lv_imgbtn_create(ui_pnlHdr);
    lv_imgbtn_set_src(ui_btnWifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wificon_png, NULL);
    lv_obj_set_width(ui_btnWifi, 46);
    lv_obj_set_height(ui_btnWifi, 40);
    lv_obj_set_x(ui_btnWifi, 423);
    lv_obj_set_y(ui_btnWifi, 1);
    lv_obj_set_style_radius(ui_btnWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_btnWifi, lv_color_hex(0x0AD100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnWifi, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_swchScrnMain = lv_switch_create(ui_pnlHdr);
    lv_obj_set_width(ui_swchScrnMain, 40);
    lv_obj_set_height(ui_swchScrnMain, 40);
    lv_obj_set_style_bg_color(ui_swchScrnMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_swchScrnMain, &ui_img_hamburger_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_swchScrnMain, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnMain, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swchScrnMain, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swchScrnMain, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swchScrnMain, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnMain, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pnlCm = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlCm, 299);
    lv_obj_set_height(ui_pnlCm, 144);
    lv_obj_set_x(ui_pnlCm, 174);
    lv_obj_set_y(ui_pnlCm, 55);
    lv_obj_clear_flag(ui_pnlCm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlCm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlCm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlCm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlCm, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlCm, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlCm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlCm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlCm, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlCm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlCmHdr = lv_obj_create(ui_pnlCm);
    lv_obj_set_width(ui_pnlCmHdr, 327);
    lv_obj_set_height(ui_pnlCmHdr, 46);
    lv_obj_set_x(ui_pnlCmHdr, 0);
    lv_obj_set_y(ui_pnlCmHdr, -29);
    lv_obj_set_align(ui_pnlCmHdr, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnlCmHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlCmHdr, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlCmHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlCmHdr, lv_color_hex(0x6D6E77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlCmHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlCmHdr, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlCmHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlCmHdr, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm = lv_label_create(ui_pnlCmHdr);
    lv_obj_set_width(ui_lblCm, lv_pct(80));
    lv_obj_set_height(ui_lblCm, lv_pct(184));
    lv_obj_set_x(ui_lblCm, 0);
    lv_obj_set_y(ui_lblCm, 6);
    lv_obj_set_align(ui_lblCm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCm, "Current Monitors");
    lv_obj_set_style_text_color(ui_lblCm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblCm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm1 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCm1, -2);
    lv_obj_set_y(ui_lblCm1, 20);
    lv_label_set_text(ui_lblCm1, "1.");
    lv_obj_set_style_text_color(ui_lblCm1, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm1, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm2 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCm2, -12);
    lv_obj_set_y(ui_lblCm2, 55);
    lv_label_set_text(ui_lblCm2, "2.");
    lv_obj_set_style_text_color(ui_lblCm2, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm3 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCm3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCm3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCm3, -12);
    lv_obj_set_y(ui_lblCm3, 90);
    lv_label_set_text(ui_lblCm3, "3.");
    lv_obj_set_style_text_color(ui_lblCm3, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm3, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm4 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCm4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCm4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCm4, 15);
    lv_obj_set_y(ui_lblCm4, 20);
    lv_obj_set_align(ui_lblCm4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCm4, "4.");
    lv_obj_set_style_text_color(ui_lblCm4, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm4, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm5 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCm5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCm5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCm5, 15);
    lv_obj_set_y(ui_lblCm5, 55);
    lv_obj_set_align(ui_lblCm5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCm5, "5.");
    lv_obj_set_style_text_color(ui_lblCm5, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm5, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCm6 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCm6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCm6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCm6, 15);
    lv_obj_set_y(ui_lblCm6, 90);
    lv_obj_set_align(ui_lblCm6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCm6, "6.");
    lv_obj_set_style_text_color(ui_lblCm6, lv_color_hex(0x60B3E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCm6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCm6, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCmD1 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCmD1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCmD1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCmD1, 18);
    lv_obj_set_y(ui_lblCmD1, 20);
    lv_label_set_text(ui_lblCmD1, "143.34 A");
    lv_obj_set_style_text_color(ui_lblCmD1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCmD1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCmD1, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCmD2 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCmD2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCmD2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCmD2, 19);
    lv_obj_set_y(ui_lblCmD2, 55);
    lv_label_set_text(ui_lblCmD2, "143.34 A");
    lv_obj_set_style_text_color(ui_lblCmD2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCmD2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCmD2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCmD3 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCmD3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCmD3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCmD3, 19);
    lv_obj_set_y(ui_lblCmD3, 90);
    lv_label_set_text(ui_lblCmD3, "143.34 A");
    lv_obj_set_style_text_color(ui_lblCmD3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCmD3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCmD3, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCmD4 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCmD4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCmD4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCmD4, 90);
    lv_obj_set_y(ui_lblCmD4, 20);
    lv_obj_set_align(ui_lblCmD4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCmD4, "143.34 A");
    lv_obj_set_style_text_color(ui_lblCmD4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCmD4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCmD4, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCmD5 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCmD5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCmD5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCmD5, 90);
    lv_obj_set_y(ui_lblCmD5, 55);
    lv_obj_set_align(ui_lblCmD5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCmD5, "143.34 A");
    lv_obj_set_style_text_color(ui_lblCmD5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCmD5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCmD5, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCmD6 = lv_label_create(ui_pnlCm);
    lv_obj_set_width(ui_lblCmD6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCmD6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCmD6, 90);
    lv_obj_set_y(ui_lblCmD6, 90);
    lv_obj_set_align(ui_lblCmD6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCmD6, "143.34 A");
    lv_obj_set_style_text_color(ui_lblCmD6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCmD6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCmD6, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlCmBrdr2 = lv_obj_create(ui_pnlCm);
    lv_obj_set_width(ui_pnlCmBrdr2, 503);
    lv_obj_set_height(ui_pnlCmBrdr2, 38);
    lv_obj_set_x(ui_pnlCmBrdr2, 86);
    lv_obj_set_y(ui_pnlCmBrdr2, 18);
    lv_obj_set_align(ui_pnlCmBrdr2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlCmBrdr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlCmBrdr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlCmBrdr2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlCmBrdr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlFlt = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlFlt, 299);
    lv_obj_set_height(ui_pnlFlt, 57);
    lv_obj_set_x(ui_pnlFlt, 174);
    lv_obj_set_y(ui_pnlFlt, 207);
    lv_obj_clear_flag(ui_pnlFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlFlt, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlFlt, lv_color_hex(0x9A9A9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlFlt, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlFlt, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlFlt, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlFlt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlFlt, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFlt = lv_label_create(ui_pnlFlt);
    lv_obj_set_width(ui_lblFlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFlt, 0);
    lv_obj_set_y(ui_lblFlt, -15);
    lv_obj_set_align(ui_lblFlt, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblFlt, "System Faults");
    lv_obj_set_style_text_color(ui_lblFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlFltD = lv_obj_create(ui_pnlFlt);
    lv_obj_set_width(ui_pnlFltD, 306);
    lv_obj_set_height(ui_pnlFltD, 46);
    lv_obj_set_x(ui_pnlFltD, 0);
    lv_obj_set_y(ui_pnlFltD, 26);
    lv_obj_set_align(ui_pnlFltD, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_pnlFltD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlFltD, lv_color_hex(0x34C94F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlFltD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlFltD, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlFltD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlFltD, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlFltD, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFltD = lv_label_create(ui_pnlFltD);
    lv_obj_set_width(ui_lblFltD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFltD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFltD, -10);
    lv_obj_set_y(ui_lblFltD, 3);
    lv_obj_set_align(ui_lblFltD, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblFltD, "No Faults");
    lv_obj_set_style_text_color(ui_lblFltD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFltD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblFltD, &ui_font_seg7_22pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlFtr = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlFtr, 299);
    lv_obj_set_height(ui_pnlFtr, 46);
    lv_obj_set_x(ui_pnlFtr, 174);
    lv_obj_set_y(ui_pnlFtr, 283);
    lv_obj_clear_flag(ui_pnlFtr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlFtr, lv_color_hex(0x36364D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlFtr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlFtr, lv_color_hex(0x09090E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlFtr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlFtr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlFtr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFtr = lv_label_create(ui_pnlFtr);
    lv_obj_set_width(ui_lblFtr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFtr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFtr, 0);
    lv_obj_set_y(ui_lblFtr, -5);
    lv_obj_set_align(ui_lblFtr, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblFtr, "Footer Panel");
    lv_obj_set_style_text_color(ui_lblFtr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFtr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlWifi = lv_obj_create(ui_scrnMain);
    lv_obj_set_width(ui_pnlWifi, 397);
    lv_obj_set_height(ui_pnlWifi, 173);
    lv_obj_set_x(ui_pnlWifi, -445);
    lv_obj_set_y(ui_pnlWifi, -21);
    lv_obj_set_align(ui_pnlWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlWifi, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlWifi, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlWifi, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlWifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlWifi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_pnlWifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_pnlWifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddWifi = lv_dropdown_create(ui_pnlWifi);
    lv_dropdown_set_options(ui_ddWifi, "Network 1\nNetwork 2\nNetwork 3");
    lv_obj_set_width(ui_ddWifi, lv_pct(100));
    lv_obj_set_height(ui_ddWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ddWifi, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ddWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddWifi, lv_color_hex(0x717171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ddWifi, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ddWifi, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtaPass = lv_textarea_create(ui_pnlWifi);
    lv_obj_set_width(ui_txtaPass, lv_pct(100));
    lv_obj_set_height(ui_txtaPass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtaPass, 1);
    lv_obj_set_y(ui_txtaPass, lv_pct(0));
    lv_obj_set_align(ui_txtaPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtaPass, "Password");
    lv_textarea_set_one_line(ui_txtaPass, true);
    lv_obj_set_style_border_color(ui_txtaPass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_txtaPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifiConnect = lv_btn_create(ui_pnlWifi);
    lv_obj_set_width(ui_btnWifiConnect, 100);
    lv_obj_set_height(ui_btnWifiConnect, 35);
    lv_obj_set_align(ui_btnWifiConnect, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btnWifiConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnWifiConnect, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblConnect = lv_label_create(ui_btnWifiConnect);
    lv_obj_set_width(ui_lblConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConnect, "Connect");

    ui_btnWifiCancel = lv_btn_create(ui_pnlWifi);
    lv_obj_set_width(ui_btnWifiCancel, 100);
    lv_obj_set_height(ui_btnWifiCancel, 35);
    lv_obj_set_align(ui_btnWifiCancel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_btnWifiCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnWifiCancel, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiCancel = lv_label_create(ui_btnWifiCancel);
    lv_obj_set_width(ui_lblWifiCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiCancel, "Close");

    ui_kbWifi = lv_keyboard_create(ui_scrnMain);
    lv_obj_set_width(ui_kbWifi, lv_pct(100));
    lv_obj_set_height(ui_kbWifi, lv_pct(50));
    lv_obj_set_x(ui_kbWifi, 0);
    lv_obj_set_y(ui_kbWifi, 160);
    lv_obj_set_align(ui_kbWifi, LV_ALIGN_BOTTOM_MID);

    ui_btnKbSubmit = lv_btn_create(ui_kbWifi);
    lv_obj_set_width(ui_btnKbSubmit, 65);
    lv_obj_set_height(ui_btnKbSubmit, 35);
    lv_obj_set_align(ui_btnKbSubmit, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_btnKbSubmit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKbSubmit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKbSubmit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKbSubmit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnKbSubmit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnKbSubmit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnKbClose = lv_btn_create(ui_kbWifi);
    lv_obj_set_width(ui_btnKbClose, 65);
    lv_obj_set_height(ui_btnKbClose, 35);
    lv_obj_set_align(ui_btnKbClose, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btnKbClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKbClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKbClose, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKbClose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnKbClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnKbClose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnOutput, ui_event_btnOutput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToManual, ui_event_btnToManual, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToFaults, ui_event_btnToFaults, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToCanbus, ui_event_btnToCanbus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddNode, ui_event_ddNode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifi, ui_event_btnWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swchScrnMain, ui_event_swchScrnMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaPass, ui_event_txtaPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiConnect, ui_event_btnWifiConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiCancel, ui_event_btnWifiCancel, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_kbWifi, ui_txtaPass);
    lv_obj_add_event_cb(ui_btnKbSubmit, ui_event_btnKbSubmit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnKbClose, ui_event_btnKbClose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_kbWifi, ui_event_kbWifi, LV_EVENT_ALL, NULL);

}
