// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrnFaults_screen_init(void)
{
    ui_scrnFaults = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnFaults, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_style_bg_color(ui_scrnFaults, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrnFaults, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scrnFaults, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrnFaults, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSysFaults = lv_obj_create(ui_scrnFaults);
    lv_obj_set_width(ui_pnlSysFaults, 466);
    lv_obj_set_height(ui_pnlSysFaults, 256);
    lv_obj_set_x(ui_pnlSysFaults, 7);
    lv_obj_set_y(ui_pnlSysFaults, 55);
    lv_obj_clear_flag(ui_pnlSysFaults, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlSysFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlSysFaults, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSysFaults, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSysFaults, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSysFaults, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSysFaults, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSysFaults, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlSysFaults, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlSysFaults, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlSysFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlSysFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlSysFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlSysFaults, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSysFaultsHdr = lv_obj_create(ui_pnlSysFaults);
    lv_obj_set_width(ui_pnlSysFaultsHdr, lv_pct(100));
    lv_obj_set_height(ui_pnlSysFaultsHdr, lv_pct(13));
    lv_obj_clear_flag(ui_pnlSysFaultsHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlSysFaultsHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlSysFaultsHdr, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSysFaultsHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlSysFaultsHdr, lv_color_hex(0x6D6E77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlSysFaultsHdr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSysFaultsHdr, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSysFaultsHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlSysFaultsHdr, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSysFltHdr = lv_label_create(ui_pnlSysFaultsHdr);
    lv_obj_set_width(ui_lblSysFltHdr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSysFltHdr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSysFltHdr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSysFltHdr, "System Faults");
    lv_obj_set_style_text_color(ui_lblSysFltHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSysFltHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSysFltHdr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSysFltHdr, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSysFaultsBody = lv_obj_create(ui_pnlSysFaults);
    lv_obj_set_width(ui_pnlSysFaultsBody, lv_pct(100));
    lv_obj_set_height(ui_pnlSysFaultsBody, lv_pct(87));
    lv_obj_set_x(ui_pnlSysFaultsBody, 0);
    lv_obj_set_y(ui_pnlSysFaultsBody, lv_pct(13));
    lv_obj_set_align(ui_pnlSysFaultsBody, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_pnlSysFaultsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlSysFaultsBody, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSysFaultsBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSysFaultsBody, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSysFaultsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSysFaultsBody, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSysFaultsBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlSysFaultsBody, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlSysFaultsBody, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlSysFaultsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlSysFaultsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlSysFaultsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlSysFaultsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlScrnSelFlt = lv_obj_create(ui_scrnFaults);
    lv_obj_set_width(ui_pnlScrnSelFlt, 140);
    lv_obj_set_height(ui_pnlScrnSelFlt, 135);
    lv_obj_set_x(ui_pnlScrnSelFlt, 0);
    lv_obj_set_y(ui_pnlScrnSelFlt, -100);
    lv_obj_clear_flag(ui_pnlScrnSelFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlScrnSelFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlScrnSelFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlScrnSelFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlScrnSelFlt, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlScrnSelFlt, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlScrnSelFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlScrnSelFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlScrnSelFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlScrnSelFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlScrnSelFlt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlScrnSelFlt, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlScrnSelFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlScrnSelFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlScrnSelFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlScrnSelFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_pnlScrnSelFlt, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlScrnSelFlt, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlScrnSelFlt, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlScrnSelFlt, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_btnToMainFlt = lv_btn_create(ui_pnlScrnSelFlt);
    lv_obj_set_width(ui_btnToMainFlt, lv_pct(100));
    lv_obj_set_height(ui_btnToMainFlt, lv_pct(33));
    lv_obj_add_flag(ui_btnToMainFlt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToMainFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToMainFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToMainFlt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToMainFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToMainFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToMainFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToMainFlt = lv_label_create(ui_btnToMainFlt);
    lv_obj_set_width(ui_lblToMainFlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToMainFlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToMainFlt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToMainFlt, "Main");

    ui_btnToManuFlt = lv_btn_create(ui_pnlScrnSelFlt);
    lv_obj_set_width(ui_btnToManuFlt, lv_pct(100));
    lv_obj_set_height(ui_btnToManuFlt, lv_pct(33));
    lv_obj_set_x(ui_btnToManuFlt, lv_pct(0));
    lv_obj_set_y(ui_btnToManuFlt, lv_pct(33));
    lv_obj_add_flag(ui_btnToManuFlt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToManuFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToManuFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToManuFlt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToManuFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToManuFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToManuFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToManuFlt = lv_label_create(ui_btnToManuFlt);
    lv_obj_set_width(ui_lblToManuFlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToManuFlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToManuFlt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToManuFlt, "Manual");

    ui_btnToCanFlt = lv_btn_create(ui_pnlScrnSelFlt);
    lv_obj_set_width(ui_btnToCanFlt, lv_pct(100));
    lv_obj_set_height(ui_btnToCanFlt, lv_pct(33));
    lv_obj_set_x(ui_btnToCanFlt, lv_pct(0));
    lv_obj_set_y(ui_btnToCanFlt, lv_pct(66));
    lv_obj_add_flag(ui_btnToCanFlt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnToCanFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnToCanFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnToCanFlt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToCanFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnToCanFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnToCanFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblToCanFlt = lv_label_create(ui_btnToCanFlt);
    lv_obj_set_width(ui_lblToCanFlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblToCanFlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblToCanFlt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblToCanFlt, "CANbus");

    ui_pnlHdrFlt = lv_obj_create(ui_scrnFaults);
    lv_obj_set_height(ui_pnlHdrFlt, 46);
    lv_obj_set_width(ui_pnlHdrFlt, lv_pct(100));
    lv_obj_clear_flag(ui_pnlHdrFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHdrFlt, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHdrFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlHdrFlt, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHdrFlt, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_pnlHdrFlt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHdrFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHdrFlt = lv_label_create(ui_pnlHdrFlt);
    lv_obj_set_width(ui_lblHdrFlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHdrFlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHdrFlt, 43);
    lv_obj_set_y(ui_lblHdrFlt, 0);
    lv_obj_set_align(ui_lblHdrFlt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblHdrFlt, "Astrodyne TDI eLink2");
    lv_obj_set_style_text_color(ui_lblHdrFlt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHdrFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swchScrnFlt = lv_switch_create(ui_pnlHdrFlt);
    lv_obj_set_width(ui_swchScrnFlt, 40);
    lv_obj_set_height(ui_swchScrnFlt, 40);
    lv_obj_set_style_bg_color(ui_swchScrnFlt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_swchScrnFlt, &ui_img_hamburger_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_swchScrnFlt, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnFlt, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swchScrnFlt, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swchScrnFlt, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swchScrnFlt, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchScrnFlt, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_btnClearFlt = lv_btn_create(ui_pnlHdrFlt);
    lv_obj_set_width(ui_btnClearFlt, 100);
    lv_obj_set_height(ui_btnClearFlt, 35);
    lv_obj_set_x(ui_btnClearFlt, -3);
    lv_obj_set_y(ui_btnClearFlt, -4);
    lv_obj_set_align(ui_btnClearFlt, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_btnClearFlt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnClearFlt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnClearFlt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnClearFlt, lv_color_hex(0xD70000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnClearFlt, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnClearFlt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnClearFlt, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblClrFlts = lv_label_create(ui_btnClearFlt);
    lv_obj_set_width(ui_lblClrFlts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblClrFlts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblClrFlts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblClrFlts, "Clear Log");
    lv_obj_set_style_text_font(ui_lblClrFlts, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tblFlt = lv_table_create(ui_pnlSysFaultsBody);
    lv_obj_set_width(ui_tblFlt, lv_pct(100));
    lv_obj_set_height(ui_tblFlt, lv_pct(100));
    lv_obj_set_align(ui_tblFlt, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_bg_color(ui_tblFlt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tblFlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tblFlt, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tblFlt, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tblFlt, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tblFlt, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_table_set_cell_value(ui_tblFlt, 0, 0, "0x0010");
    lv_table_set_cell_value(ui_tblFlt, 0, 1, "12:58");
    lv_table_set_cell_value(ui_tblFlt, 0, 2, "SLFT-RMP_<AMPS");
    lv_table_set_cell_value(ui_tblFlt, 0, 3, "Self Test Circuit Test REFCELL4 Failed (did not = precision voltage) ");
    lv_table_set_cell_value(ui_tblFlt, 1, 0, "Name");
    lv_table_set_col_width(ui_tblFlt, 0, 55);
    lv_table_set_col_width(ui_tblFlt, 1, 45);
    lv_table_set_col_width(ui_tblFlt, 2, 140);
    lv_table_set_col_width(ui_tblFlt, 3, 217);

    lv_obj_add_event_cb(ui_btnToMainFlt, ui_event_btnToMainFlt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToManuFlt, ui_event_btnToManuFlt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToCanFlt, ui_event_btnToCanFlt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swchScrnFlt, ui_event_swchScrnFlt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnClearFlt, ui_event_btnClearFlt, LV_EVENT_ALL, NULL);

}
