// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrnManu_screen_init(void)
{
    ui_scrnManu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnManu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrnManu, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrnManu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scrnManu, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrnManu, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlHdr1 = lv_obj_create(ui_scrnManu);
    lv_obj_set_height(ui_pnlHdr1, 50);
    lv_obj_set_width(ui_pnlHdr1, lv_pct(103));
    lv_obj_set_x(ui_pnlHdr1, -10);
    lv_obj_set_y(ui_pnlHdr1, -5);
    lv_obj_clear_flag(ui_pnlHdr1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHdr1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHdr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnlHdr1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHdr1, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_pnlHdr1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_pnlHdr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHdr1 = lv_label_create(ui_pnlHdr1);
    lv_obj_set_width(ui_lblHdr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHdr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHdr1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblHdr1, "Astrodyne TDI eLink2 Node");
    lv_obj_set_style_text_color(ui_lblHdr1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHdr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddNode1 = lv_dropdown_create(ui_pnlHdr1);
    lv_dropdown_set_options(ui_ddNode1, "1 \n2 \n3 \n4 ");
    lv_obj_set_width(ui_ddNode1, 46);
    lv_obj_set_height(ui_ddNode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddNode1, -15);
    lv_obj_set_y(ui_ddNode1, 0);
    lv_obj_set_align(ui_ddNode1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ddNode1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ddNode1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ddNode1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddNode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddNode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ddNode1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ddNode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddNode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddNode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddNode1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddNode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ddNode1), LV_TEXT_ALIGN_RIGHT,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(lv_dropdown_get_list(ui_ddNode1), LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddMenu1 = lv_dropdown_create(ui_pnlHdr1);
    lv_dropdown_set_options(ui_ddMenu1, "Main\nMode Select\nTesting\nThread Info");
    lv_dropdown_set_selected_highlight(ui_ddMenu1, false);
    lv_obj_set_width(ui_ddMenu1, 36);
    lv_obj_set_height(ui_ddMenu1, 40);
    lv_obj_set_x(ui_ddMenu1, 10);
    lv_obj_set_y(ui_ddMenu1, 3);
    lv_obj_set_align(ui_ddMenu1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ddMenu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddMenu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ddMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddMenu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ddMenu1, &ui_img_hamburger_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ddMenu1, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddMenu1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_pnlSre2 = lv_obj_create(ui_scrnManu);
    lv_obj_set_width(ui_pnlSre2, 299);
    lv_obj_set_height(ui_pnlSre2, 175);
    lv_obj_set_x(ui_pnlSre2, 174);
    lv_obj_set_y(ui_pnlSre2, 55);
    lv_obj_clear_flag(ui_pnlSre2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlSre2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlSre2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSre2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSre2, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSre2, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSre2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSre2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlSre2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlSre2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSreHdr2 = lv_obj_create(ui_pnlSre2);
    lv_obj_set_width(ui_pnlSreHdr2, 327);
    lv_obj_set_height(ui_pnlSreHdr2, 46);
    lv_obj_set_x(ui_pnlSreHdr2, 0);
    lv_obj_set_y(ui_pnlSreHdr2, -29);
    lv_obj_set_align(ui_pnlSreHdr2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnlSreHdr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlSreHdr2, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSreHdr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSreHdr2, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSreHdr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlSreHdr2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSre2 = lv_label_create(ui_pnlSreHdr2);
    lv_obj_set_width(ui_lblSre2, lv_pct(80));
    lv_obj_set_height(ui_lblSre2, lv_pct(184));
    lv_obj_set_x(ui_lblSre2, 0);
    lv_obj_set_y(ui_lblSre2, 6);
    lv_obj_set_align(ui_lblSre2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSre2, "Electrode Readbacks");
    lv_obj_set_style_text_color(ui_lblSre2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSre2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSre2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSre2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl11 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl11, -10);
    lv_obj_set_y(ui_lblSreCl11, 25);
    lv_label_set_text(ui_lblSreCl11, "1");
    lv_obj_set_style_text_color(ui_lblSreCl11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl11, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl12 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl12, -10);
    lv_obj_set_y(ui_lblSreCl12, 65);
    lv_label_set_text(ui_lblSreCl12, "2");
    lv_obj_set_style_text_color(ui_lblSreCl12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl12, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl13 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl13, -10);
    lv_obj_set_y(ui_lblSreCl13, 105);
    lv_label_set_text(ui_lblSreCl13, "3");
    lv_obj_set_style_text_color(ui_lblSreCl13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl13, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl14 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl14, 10);
    lv_obj_set_y(ui_lblSreCl14, 25);
    lv_obj_set_align(ui_lblSreCl14, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSreCl14, "4");
    lv_obj_set_style_text_color(ui_lblSreCl14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl14, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl1D2 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl1D2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl1D2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl1D2, 10);
    lv_obj_set_y(ui_lblSreCl1D2, 26);
    lv_label_set_text(ui_lblSreCl1D2, "| 143.34 A");
    lv_obj_set_style_text_color(ui_lblSreCl1D2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl1D2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl1D2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl2D2 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl2D2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl2D2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl2D2, 10);
    lv_obj_set_y(ui_lblSreCl2D2, 66);
    lv_label_set_text(ui_lblSreCl2D2, "| 143.34 A");
    lv_obj_set_style_text_color(ui_lblSreCl2D2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl2D2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl2D2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl3D2 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl3D2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl3D2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl3D2, 10);
    lv_obj_set_y(ui_lblSreCl3D2, 106);
    lv_label_set_text(ui_lblSreCl3D2, "| 143.34 A");
    lv_obj_set_style_text_color(ui_lblSreCl3D2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl3D2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl3D2, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl4D4 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl4D4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl4D4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl4D4, 90);
    lv_obj_set_y(ui_lblSreCl4D4, 26);
    lv_obj_set_align(ui_lblSreCl4D4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSreCl4D4, "| 143.34 A");
    lv_obj_set_style_text_color(ui_lblSreCl4D4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl4D4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl4D4, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl15 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl15, 10);
    lv_obj_set_y(ui_lblSreCl15, 65);
    lv_obj_set_align(ui_lblSreCl15, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSreCl15, "5");
    lv_obj_set_style_text_color(ui_lblSreCl15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl15, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl16 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl16, 10);
    lv_obj_set_y(ui_lblSreCl16, 105);
    lv_obj_set_align(ui_lblSreCl16, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSreCl16, "6");
    lv_obj_set_style_text_color(ui_lblSreCl16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl16, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl4D5 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl4D5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl4D5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl4D5, 90);
    lv_obj_set_y(ui_lblSreCl4D5, 66);
    lv_obj_set_align(ui_lblSreCl4D5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSreCl4D5, "| 143.34 A");
    lv_obj_set_style_text_color(ui_lblSreCl4D5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl4D5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl4D5, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSreCl4D6 = lv_label_create(ui_pnlSre2);
    lv_obj_set_width(ui_lblSreCl4D6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSreCl4D6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSreCl4D6, 90);
    lv_obj_set_y(ui_lblSreCl4D6, 106);
    lv_obj_set_align(ui_lblSreCl4D6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSreCl4D6, "| 143.34 A");
    lv_obj_set_style_text_color(ui_lblSreCl4D6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSreCl4D6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSreCl4D6, &ui_font_seg7Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSre3 = lv_obj_create(ui_scrnManu);
    lv_obj_set_width(ui_pnlSre3, 299);
    lv_obj_set_height(ui_pnlSre3, 175);
    lv_obj_set_x(ui_pnlSre3, 17);
    lv_obj_set_y(ui_pnlSre3, 134);
    lv_obj_clear_flag(ui_pnlSre3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlSre3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlSre3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSre3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSre3, lv_color_hex(0x202226), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSre3, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSre3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSre3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlSre3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlSre3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSreHdr3 = lv_obj_create(ui_pnlSre3);
    lv_obj_set_width(ui_pnlSreHdr3, 327);
    lv_obj_set_height(ui_pnlSreHdr3, 46);
    lv_obj_set_x(ui_pnlSreHdr3, 0);
    lv_obj_set_y(ui_pnlSreHdr3, -29);
    lv_obj_set_align(ui_pnlSreHdr3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnlSreHdr3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlSreHdr3, lv_color_hex(0x545A66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSreHdr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSreHdr3, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSreHdr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlSreHdr3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSre3 = lv_label_create(ui_pnlSreHdr3);
    lv_obj_set_width(ui_lblSre3, lv_pct(80));
    lv_obj_set_height(ui_lblSre3, lv_pct(184));
    lv_obj_set_x(ui_lblSre3, 0);
    lv_obj_set_y(ui_lblSre3, 6);
    lv_obj_set_align(ui_lblSre3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSre3, "Set Points");
    lv_obj_set_style_text_color(ui_lblSre3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSre3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSre3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSre3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ddNode1, ui_event_ddNode1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddMenu1, ui_event_ddMenu1, LV_EVENT_ALL, NULL);

}
