/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdio.h"
#include "globals.h"
#include "stdlib.h"
#include "iccpfuncs.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_SLIDER_0 (GUI_ID_USER + 0x05)
#define ID_EDIT_0 (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

extern WM_HWIN Createiccp_main(void);
extern WM_HWIN Createlcdkeypad(void);
char strSaveBtnText[8];


// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "iccp_cv", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Home_Btn", ID_BUTTON_0, 255, 10, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Set", ID_BUTTON_1, 255, 65, 45, 45, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Volts_txt", ID_TEXT_0, 0, 43, 106, 66, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Voltage Set", ID_TEXT_1, 100, 20, 100, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 0, 5, 52, 181, 8, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
	{ EDIT_CreateIndirect,     0,        ID_EDIT_0,      100,  43, 110,  50, 0, 5},
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
//static int sldrcnt=0;
static void _cbDialog(WM_MESSAGE * pMsg) 
{
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	//	BUTTON_SKINFLEX_PROPS BtnProps;
	//	FRAMEWIN_SKINFLEX_PROPS FrmProps;
  // USER START (Optionally insert additional variables)
  
	char dbgstr[8];
	static int setcnt=0,editcnt=0;
	// USER END

  switch (pMsg->MsgId)
	{
		case WM_INIT_DIALOG:
		{
			printf("Init CV Dialog");
			//               
			// Initialization of 'iccp_cv'
			//               
			hItem = pMsg->hWin;
			FRAMEWIN_SetText(hItem, "CV Adjust");
			FRAMEWIN_SetTitleHeight(hItem, 20);
			FRAMEWIN_SetClientColor(hItem,GUI_WHITE);  //FRAMEWIN_CLIENTCOLOR_DEFAULT);
			FRAMEWIN_SetSkin(hItem,FRAMEWIN_SKIN_FLEX);
			//
			// Initialization of 'Home_Btn'
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
			BUTTON_SetText(hItem, "HOME");
			BUTTON_SetFont(hItem, GUI_FONT_13B_ASCII);
			BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
			//
			//
			// Initialization of 'Save'
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
			BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
			BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
			BUTTON_SetText(hItem, "Set");
			//
			//
			// Initialization of 'Volts_txt'
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
			TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
			TEXT_SetFont(hItem, GUI_FONT_D24X32);
			//                                    
			//sprintf(dbgstr,"%3.2f",(float)cvmode_vset/10);
			//TEXT_SetText(hItem,dbgstr );
			//TEXT_SetTextColor(hItem, GUI_BLUE);
			//                                                                                    
			// Initialization of 'Volts Label'                                                          
			//                                                                                    
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
			TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
			TEXT_SetFont(hItem, GUI_FONT_20_1);
			TEXT_SetTextColor(hItem, 0x00FF0000);
			//USER START (Optionally insert additional code for further widget initialization)
			//
			// Initialization of 'Slider'
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
			SLIDER_SetWidth(hItem, 10);
			SLIDER_SetFocusColor(hItem, GUI_RED);
			SLIDER_SetValue(hItem,cvmode_vset); 
			SLIDER_SetSkin(hItem,SLIDER_SKIN_FLEX);
			SLIDER_SetRange(hItem, 50, 650);
			SLIDER_SetNumTicks(hItem, 60);
			
			// Set Edit Box
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);  /* Get the handle of the edit widget */
			EDIT_SetFont(hItem, GUI_FONT_D24X32);
			EDIT_SetTextColor(hItem,EDIT_CI_ENABLED, GUI_BLUE);//0x000303E7);
			EDIT_SetTextAlign(hItem,GUI_TA_CENTER | GUI_TA_VCENTER);
			sprintf(dbgstr,"%2.1f",(float)cvmode_vset/10);
			EDIT_SetText(hItem, dbgstr);                   /* Set text */
			
			WM_InvalidateWindow(pMsg->hWin);
			// USER END
			break;
		}
		case WM_NOTIFY_PARENT:
		{
				Id    = WM_GetId(pMsg->hWinSrc);
				NCode = pMsg->Data.v;
				printf("ID:%i  NCode:%i \r\n",Id,NCode);
							
				switch(Id) 
				{
						case ID_BUTTON_0: // Notifications sent by 'Home_Btn'
						{
							switch(NCode) 
							{
									case WM_NOTIFICATION_CLICKED:
										break;
									case WM_NOTIFICATION_RELEASED:
											systemstatus_s.gui_scn_state_cv = INIT_DIALOG;
											Createiccp_main();
										break;
							}//end switch NCode
							break;
						}
						case ID_BUTTON_1: // Notifications sent by 'Save'
						{
							switch(NCode) 
							{
									case WM_NOTIFICATION_CLICKED:
										// USER START (Optionally insert code for reacting on notification message)
										// USER END
										break;
									case WM_NOTIFICATION_RELEASED:
										// USER START (Optionally insert code for reacting on notification message)
										hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
										
										// see what mode the btn is in 
										BUTTON_GetText(hItem, strSaveBtnText, sizeof(strSaveBtnText));
										
										if(	systemstatus_s.gui_scn_state_cv == INIT_DIALOG)
										{
											systemstatus_s.gui_scn_state_cv = SETVAL;// back to init after save pressed
											BUTTON_SetText(hItem, "Save");
											hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
											EDIT_SetTextColor(hItem,1,GUI_RED);
											EDIT_EnableBlink(hItem, 500, 1);
											
											if(setcnt>2)
											{
												setcnt=0;
												Createlcdkeypad();
											}
											
										}
										else if(systemstatus_s.gui_scn_state_cv == SETVAL)
										{
											setcnt=0;//reset so keyboatd does not open
											systemstatus_s.gui_scn_state_cv = INIT_DIALOG;// back to init after save pressed
											BUTTON_SetText(hItem, "Set");
											hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
											EDIT_GetText(hItem,dbgstr,sizeof(dbgstr));
											//convert str contents of edit box to int to be saved in volts var
											cvmode_vsettmp = (unsigned int)(atof(dbgstr)*10);
										
											
											EDIT_SetTextColor(hItem,1,GUI_BLUE);
											EDIT_EnableBlink(hItem, 500, 0);
											cvmode_vset = cvmode_vsettmp;
											printf("CVtmp:%2.1f  CV:%2.1f \r\n",(float)cvmode_vsettmp/10,(float)cvmode_vset/10);
															
											//set slider to int val
											hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
											SLIDER_SetValue(hItem,cvmode_vsettmp); 
										}
										// USER END
										break;
									// USER START (Optionally insert additional code for further notification handling)
									// USER END
							}
							break;//break ID_BUTTON_1
						}
						case ID_SLIDER_0: // Notifications sent by 'Slider'
						{
							switch(NCode) {
									case WM_NOTIFICATION_CLICKED:
										// USER START (Optionally insert code for reacting on notification message)
										// USER END
										break;
									case WM_NOTIFICATION_RELEASED:
										break;
									case WM_NOTIFICATION_VALUE_CHANGED:
										if(	systemstatus_s.gui_scn_state_cv == INIT_DIALOG )
										{
												systemstatus_s.gui_scn_state_cv = SETVAL;// back to init after save pressed
												hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
												BUTTON_SetText(hItem, "Save");
												hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
												EDIT_SetTextColor(hItem,1,GUI_RED);
												EDIT_EnableBlink(hItem, 250, 1);
										}
										
										if(	systemstatus_s.gui_scn_state_cv == SETVAL )
										{
												// update variable with new slider val
												hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
												cvmode_vsettmp = (unsigned int)SLIDER_GetValue(hItem); 
												printf("CV:%3.2f \r\n",(float)cvmode_vsettmp/10);
												sprintf(dbgstr,"%2.1f",(float)cvmode_vsettmp/10);
											
												//hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
												//TEXT_SetText(hItem,dbgstr);
											
												hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
												EDIT_SetText(hItem,dbgstr);
										}
										// USER END
									break;
									}
						break;
						}
						case ID_EDIT_0: // Notifications sent by 'Edit Volts Display'
						{
									switch(NCode) 
									{
											case WM_NOTIFICATION_CLICKED:
												// USER START (Optionally insert code for reacting on notification message)
												
												// USER END
												break;
											case WM_NOTIFICATION_RELEASED:
												// USER START (Optionally insert code for reacting on notification message)
												editcnt++;
												if(editcnt>2 && systemstatus_s.gui_kybrd_state1 != KYBRDUP)
												{
													editcnt=0;
													systemstatus_s.gui_kybrd_state1 = KYBRDUP;
													Createlcdkeypad();
												}
												// USER END
												break;
											case WM_NOTIFICATION_VALUE_CHANGED:
												// USER START (Optionally insert code for reacting on notification message)
												// USER END
												break;
									}
							// USER END
							break;
						}
				}//end switch Id
				default:
						WM_DefaultProc(pMsg);
				break;
  }// end NOTIFY PARENT MSG
	}//end switch MSGID
}//end func	

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/


/*********************************************************************
*
*       Createiccp_cv
*/
WM_HWIN Createiccp_cv(void);

WM_HWIN Createiccp_cv(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  
	systemstatus_s.gui_scn_state_cv = INIT_DIALOG;
	
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
