<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<title>AstrodyneTDI, Inc ICCP Host Controller</title>
<link href="/atdi_iccp.css" rel="stylesheet" type="text/css">
<script src="/iccpdynavars.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one">
<div id="page">

<div style="padding:0 0 0 35px"><img src="/logo_astrodyne.gif" width="40%" alt="AstrodyneTDI"></div>

<div style="padding:0 0 0 25px" id="navcontainer">
<ul id="navlist">
<li id="active"><a href="/index.htm">Node Status</a></li>
<li><a href="/cfgcv.htm">CV Cfg</a></li>
<li><a href="/cfgci.htm">CI Cfg</a></li>
<li><a href="/cfgcp.htm">CP Cfg</a></li>
</ul>
</div>